### ISSUE TITLE
Windows Spider Solitaire save file

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#137]
```yaml
meta:
  id: spider_sav
  title: Windows Spider Solitaire save file
  application:
    - Windows Spider Solitaire
  file-extension: sav
doc-ref: http://www.genialitaet.de/fw/Spider.sav
doc:|
  A file format used by Spyder Solitaire shipped with Windows XP for saving games.
```

WiP: https://github.com/KOLANICH/kaitai_struct_formats/blob/spider_sav/game/spider_sav.ksy
