### ISSUE TITLE
Apple AWDL

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#151]
```yaml
meta:
  id: apple_awdl
  title: Apple Wireless Direct Link
  application:
    - AirDrop
  xref:
    wikidata: Q406655

doc: | 
  Apple Wireless Direct Link is a proprietaty protocol used in Apple software and devices for peer-to-peer connections. It utilizes Wi-Fi for data transfer and Bluetooth Low Energy for sending metainformation to reduce power consumption.
doc-ref:
  - "https://arxiv.org/abs/1808.03156"
  - "https://github.com/seemoo-lab/owl"
  - "https://github.com/seemoo-lab/wireshark-awdl"
  - "https://github.com/Tarlab/tarAWDL"
  - "https://github.com/seemoo-lab/opendrop"
```
