### ISSUE TITLE
Microsoft CogNitive ToolKit

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#152]
```yaml
meta:
  id: cntk
  title: Microsoft CogNitive ToolKit Computation NeTworK
  file-extension: model
  xref:
    wikidata: Q23680120
  endian: le
  encoding: UTF-16le
  license: MIT

doc: |
  A native CNTK format for serialization of a computation graph. These graphs are usually used to store machine-learning models, like neural networks and gradient boosted decision trees ensembles.
  The list of pretrained models is here: https://github.com/Microsoft/CNTK/blob/master/PretrainedModels/download_model.py
  Only some of them have this format.

doc-ref:
  - https://github.com/Microsoft/CNTK
```

```yaml
WiP:
  - https://github.com/KOLANICH/kaitai_struct_formats/blob/CNTK/scientific/data_science/cntk.ksy
issues:
  block: [ 435, 459 ]
```
