### ISSUE TITLE
QEMU Copy-on-Write 2

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#154]
```yaml
meta:
  id: qcow2
  title: QEMU Copy-on-Write 2
  application:
    - QEMU
    - VirtualBox
    - VMWare Workstation
    - libqcow
  file-extension: qcow
  xref: 
    forensicswiki: QCOW_Image_Format 
    wikidata: Q1052000
  endian: be
  encoding: utf-8
doc: |
  A native QEMU image file format.
  A qcow2 image file is organized in units of constant size, which are called (host) clusters. A cluster is the unit in which all allocations are done, both for actual guest data and for image metadata.
  Likewise, the virtual disk as seen by the guest is divided into (guest) clusters of the same size.
  If the image has a backing file then the backing file name should be stored in the remaining space between the end of the header extension area and the end of the first cluster. It is not allowed to store other data here, so that an implementation can safely modify the header and add extensions without harming data of compatible features that it doesn't support. Compatible features that need space for additional data can use a header extension.

doc-ref:
  - https://github.com/qemu/qemu/blob/master/docs/interop/qcow2.txt
  - https://github.com/qemu/qemu/blob/master/block/qcow2.h
  - https://github.com/qemu/qemu/blob/master/block/qcow2.c
  - https://www.virtualbox.org/svn/vbox/trunk/src/VBox/Storage/QCOW.cpp
```

```yaml
WiP:
  - https://github.com/KOLANICH/kaitai_struct_formats/blob/qcow/filesystem/qcow2.ksy
issues:
  block: [ null ] # there used to be one, but I don't remember which one
```
