### ISSUE TITLE
Android Parcel

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#155]
```yaml
meta:
  id: android_parcel
  title: Android Parcel
  application:
    - Android
    - Android Binder
  xref:
    wikidata: Q17121613
  license: Apache-2.0
  encoding: utf-16
  endian: le # in fact machine endianess, but most of kachines are LE

doc: |
  Container for a message (data and object references) that can be sent through an IBinder.  A Parcel can contain both flattened data that will be unflattened on the other side of the IPC (using the various methods here for writing specific types, or the general Parcelable interface), and references to live IBinder objects that will result in the other side receiving a proxy IBinder connected with the original IBinder in the Parcel.
  Parcel is **not** a general-purpose serialization mechanism.  This class (and the corresponding Parcelable API for placing arbitrary objects into a Parcel) is designed as a high-performance IPC transport.  As such, it is not appropriate to place any Parcel data in to persistent storage: changes in the underlying implementation of any of the data in the Parcel can render older data unreadable.


doc-ref:
  - https://github.com/android/platform_frameworks_base/blob/master/core/java/android/os/Parcel.java
  - https://developer.android.com/reference/android/os/Parcel
```

```yaml
WiP:
  - https://github.com/KOLANICH/kaitai_struct_formats/blob/android_parcel/serialization/android_parcel.ksy
```
