### ISSUE TITLE
OpenAL HRIR/HRTF

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#156]
```yaml
meta:
  id: openal_hrir
  title: OpenAL Head-Related Impulse Response
  application:
    - OpenAL
  file-extension: mhr
  xref:
    wikidata:
      - Q1432854
      - Q910775
  endian: le

doc: |
  The format to store head-related impulse responses to have binaural spatial sound in the apps using OpenAL.
  The samples can be found by the link: https://github.com/kcat/openal-soft/tree/master/hrtf
doc-ref: https://github.com/kcat/openal-soft/blob/master/docs/hrtf.txt
```

```yaml
WiP:
  - https://github.com/KOLANICH/kaitai_struct_formats/blob/openal_hrir/media/openal_hrir.ksy
issues:
  block: [291]
```
