### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct_formats#158]
@sophoslabs have started a WebAssembly parser:

* [webassembly.ksy](https://github.com/sophoslabs/WebAssembly/blob/master/Tools/Kaitai-Wasm/webassembly.ksy)
* [Python disassembler based on that .ksy](https://github.com/sophoslabs/WebAssembly/blob/master/Tools/Kaitai-Wasm/wasm-disassembler.py)

```yaml
meta:
  id: webassembly
  title: Web Assembly parser
  file-extension: wasm
  endian: le
  license: CC0-1.0
  file-extension:
    - wasm
  imports:
    - vlq_base128_le
doc: |
  WebAssembly is a web standard that defines a binary format and a corresponding
  assembly-like text format for executable code in Web pages. It is meant to
  enable executing code nearly as fast as running native machine code.
doc-ref: https://github.com/WebAssembly/design/blob/master/BinaryEncoding.md
```
