### ISSUE TITLE
Alcohol / DaemonTools .MDF

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#165]
```yaml
meta:
  id: mdf
  title: "DaemonTools and Alcohol 120% proprietary format"
  application:
    - Alcohol 120%
    - Alcohol 62%
    - DaemonTools
  file-extension: mdf
  xref:
    justsolve: MDF_and_MDS
    wikidata: Q3853674
  endian: le
  license: LGPL-3.0 # or maybe MIT: https://github.com/discimagechef/DiscImageChef/blob/master/LICENSE.MIT
doc: |
  Native file format of Alcohol and DaemonTools. Stores a disk image.
doc-ref:
- https://github.com/discimagechef/DiscImageChef/tree/master/DiscImageChef.DiscImages/Alcohol120
```

```yaml
WiP:
  - https://github.com/KOLANICH/kaitai_struct_formats/blob/alcohol_daemontools_mdf/filesystem/mdf.ksy
```
