### ISSUE TITLE
CERN ROOT

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#166]
```yaml
meta:
  id: root
  title: CERN ROOT
  application: CERN ROOT
  file-extension: root
  xref:
    justsolve: ROOT
    wikidata: Q947171
  endian: be
  imports:
    - /common/uuid
doc: | 
  File format used by scientific software CERN ROOT.
doc-ref:
  - "https://root.cern.ch/doc/master/classTFile.html"
  - "https://github.com/root-mirror/root/blob/master/documentation/users-guide/InputOutput.md"
  - "https://root.cern.ch/root/htmldoc/guides/users-guide/ROOTUsersGuide.html#inputoutput"
```

```yaml
WiP:
  - https://github.com/KOLANICH/kaitai_struct_formats/blob/root/scientific/root.ksy
```
