### ISSUE TITLE
Smile serialization format

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#167]
```yaml
meta:
  id: smile
  title: Smile
  file-extension: sml
  xref:
    mime: application/x-jackson-smile
    wikidata: Q17081599
  endian: le
  encoding: UTF-8
  -version: "1.0.4 (12-May-2013)"
  license: BSD-2-Clause

doc: |
  Efficient JSON-compatible binary format: "Smile"
  "Smile" is codename for an efficient JSON-compatible binary data format, initially developed by Jackson JSON processor project team.
  Its logical data model is same as that of JSON, so it can be considered a "Binary JSON" format.
doc-ref: https://github.com/FasterXML/smile-format-specification
```

```yaml
WiP:
  - https://github.com/KOLANICH/kaitai_struct_formats/blob/smile/serialization/smile.ksy
```
