### ISSUE TITLE
RFC 4122 UUID/GUID

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#168]
```yaml
meta:
  id: uuid
  title: UUID/GUID
  xref:
    forensicswiki: Universally Unique Identifier
    iso: "9834-8:2005"
    justsolve: UUID
    rfc: 4122
    wikidata: Q195284
  endian: be
  license: Unlicense
doc: a UUID according to RFC 4122
doc-ref: https://www.ietf.org/rfc/rfc4122.txt
```

```yaml
WiP:
  - https://github.com/KOLANICH/kaitai_struct_formats/blob/uuid/common/uuid.ksy
```
