### ISSUE TITLE
Tcl cookfs

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#169]
```yaml
meta:
  id: tcl_cookfs
  title: Tcl cookfs
  application: tcl

doc: |
  A serialization Tcl virtual fioe system

doc-ref: # MANDATORY.
  - https://sourceforge.net/p/cookit/code/HEAD/tree/cookfs/generic/cookfs.c
  - https://tclcommunityassociation.org/wub/proceedings/Proceedings-2010/WojciechKocjan/Cookfs-Paper/Cookfs-Paper.pdf
```
