### ISSUE TITLE
Metakit

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#170]
```yaml
meta:
  id: metakit
  title: Metakit
  application: Metakit
  file-extension: mk
  xref:
    wikidata: Q1924669

doc: |
  An embeddable database format.

doc-ref: # MANDATORY.
  - https://equi4.com/metakit/
  - https://git.jeelabs.org/jcw/metakit
  - https://github.com/electric-cloud/metakit/tree/master/src
```
