### ISSUE TITLE
FreeArc arc

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#171]
```yaml
meta:
  id: freearc_arc
  title: FreeArc
  application: FreeArc
  file-extension: arc
  xref:
    wikidata: Q3495962

doc: |
  Native archive format of FreeArc archiver.

doc-ref:
  - https://github.com/Bulat-Ziganshin/FA
```
