### ISSUE TITLE
PeaZip pea

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#172]
```yaml
meta:
  id: peazip_pea
  title: PeaZip archive format
  application: PeaZip
  file-extension: pea
  xref:
    wikidata: Q1275912

doc: |
  native file format of PeaZip archiver.

doc-ref: # MANDATORY.
  - https://github.com/giorgiotani/PeaZip/releases
```
