### ISSUE TITLE
NI LabView vi

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#174]
```yaml
meta:
  id: labview_vi
  title: LabView virtual instrument
  application: LabView
  file-extension: vi
  xref: 
    wikidata: Q746261

doc: |
  NI LabView is a popular IDE for visual programming. Usages are from children toys like LEGO Mindstorms to ~~children toys~~experiment automation, digital signal processing and machine learning pipelines.

doc-ref:
  - https://github.com/tomsoftware/VI-Explorer
  - https://github.com/tomsoftware/VI-Explorer-VI
```
