### ISSUE TITLE
Lytro Light Field Picture

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#175]
```yaml
meta:
  id: lytro_lfp
  title: Lytro Light Field Picture
  application:
    - Lytro Cameras
    - Lytro Desktop
  file-extension: lfp
  xref:
    wikidata: Q2984629

doc: |
  Native file format of Lytro light field cameras.

doc-ref:
  - https://github.com/nrpatel/lfptools
  - https://github.com/behnam/python-lfp-reader
  - https://github.com/hahnec/plenopticam
  - https://github.com/imageio/imageio/blob/master/imageio/plugins/lytro.py
  - https://eclecti.cc/computervision/reverse-engineering-the-lytro-lfp-file-format
  - http://optics.miloush.net/lytro/TheFileFormat.aspx
```
