### ISSUE TITLE
ZX Spectrum TZX tape image

### ISSUE THREAD

**Issue by dgelessus** [kaitai-io/kaitai_struct_formats#178]
```yaml
meta:
  id: zx_spectrum_tzx
  title: ZX Spectrum TZX tape image
  file-extension: tzx
  xref:
    justsolve: TZX
    pronom: fmt/1000

doc: |
  The TZX tape image format for tapes for the ZX Spectrum (and compatibles/derivatives/related machines). Compared to the very basic TAP format, which can only store standard-format tape data as used by the ROM load/save routines, the TZX format can also store various kinds of turbo loader and copy protection data, as well as arbitrary audio data if necessary. The TZX format also supports various kinds of metadata, including human-readable information about the tape, machine-readable information about the hardware that the tape is intended for, and control instructions to affect how the tape is loaded by an emulator.

doc-ref:
  - https://www.worldofspectrum.org/TZXformat.html
  - http://www.zx-modules.de/fileformats/tzxformat.html
```
