### ISSUE TITLE
.NET Remoting Binary Format (NRBF)

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct_formats#179]
```yaml
meta:
  id: nrbf
  endian: le
  application: .NET
  imports:
    - vlq_base128_le

doc: |
  .NET binary serialisation format (BinaryFormatter)
```

@trejkaz started WiP here: https://github.com/trejkaz/nrbf.ksy
