### ISSUE TITLE
FTDI232 USB to RS232 protocol

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#186]
```yaml
meta:
  id: ftdi232
  title: FTDI232 protocol
  endian: le
  license: MIT
doc: |
  Protocol for FTDI232 chips.
  Most of the stuff is set via control transactions, data is usually passed as control transaction arguments: value and index. Obviously, Kaitai Struct cannot describe protocols where the data is transfered in fields of other protocols, we need a separate Verilog-based DSL for that.
  But sometimes the stuff is set up as control commands payload.

doc-ref:
  - https://github.com/felHR85/UsbSerial
```

```yaml
WiP: https://github.com/KOLANICH/kaitai_struct_formats/tree/ftdi
```
