### ISSUE TITLE
ZStandard compression

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#187]
```yaml
meta:
  id: zstd
  title: ZStandard compression format
  file-extension: zst
  xref: 
    mime: application/zstd
    rfc: 8478
    wikidata: Q26737171
  license: Unlicense
  endian: le
doc: |
  ZStandard compressed frame.
doc-ref:
  - https://github.com/facebook/zstd/blob/master/doc/zstd_compression_format.md
  - https://tools.ietf.org/html/rfc8478
```
```yaml
WiP: https://github.com/KOLANICH/kaitai_struct_formats/tree/zstd
```
