### ISSUE TITLE
Pepakura PDO

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#189]
```yaml
meta:
  id: pepakura_pdo
  endian: le
  file-extension: pdo
  title: Pepakura PDO v3
  application:
   - Pepakura Designer
   - Pepakura Reader
  encoding: UTF-8
doc: |
  A proprietary format of popular software for creation of (ki|o)rigami.
  Files for testing: https://github.com/daeken/PepakuraReverse/tree/master/pdos
doc-ref:
  - https://github.com/daeken/PepakuraReverse
```

```yaml
WiP: https://github.com/KOLANICH/kaitai_struct_formats/tree/pepakura_pdo
```
