### ISSUE TITLE
Origin opj

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#190]
```yaml
meta:
  id: origin_opj
  title: Origin project
  application:
    - Origin
    - OriginPro
    - Origin Viewer
  file-extension: opj
  xref:
    wikidata: Q1307239
  endian: be
  license: ?

doc: |
  Origin is a scientific spreadsheet editor. It uses an own proprietary format.
  
  Test files:
    https://github.com/aperbook/APER/tree/master/Origin
    https://github.com/choderalab/bayesian-itc/tree/master/data/Mg2-EDTA/Mg2EDTA
    https://github.com/aitap/Ropj/blob/master/inst/test.opj
    https://github.com/p4db/p4db-data/raw/master/icnp.opj
    https://rdmc-test.nottingham.ac.uk/bitstream/handle/internal/76/Photocurrent%20spectra%20of%20InSe-Indium%20oxide%20p-n%20junction.opj
    https://rdmc-test.nottingham.ac.uk/bitstream/handle/internal/76/Effect%20of%20thermal%20annealing%20with%20increasing%20temperature.opj
    https://rdmc-test.nottingham.ac.uk/bitstream/handle/internal/69/Grafting%20from%20%28thermal%29%20v%20time.opj
    https://rdmc-test.nottingham.ac.uk/bitstream/handle/internal/69/Grafting%20to%20IR%20PDMSvThiol.opj
    https://rdmc-test.nottingham.ac.uk/bitstream/handle/internal/69/Grafting%20to%20IR%20results%20bar.opj
    https://rdmc-test.nottingham.ac.uk/bitstream/handle/internal/69/Polymer%20kinetics%20solution.opj
doc-ref:
  - https://github.com/jgonera/openopj/blob/master/docs/opj_format.markdown
  - https://github.com/Saluev/python-liborigin2
  - https://github.com/swharden/PyOriginTools
  - https://sourceforge.net/p/liborigin/git/ci/master/tree/
  - https://github.com/vpaeder/terapy/blob/master/terapy/files/origin.py
  - https://sourceforge.net/p/scidavis/svn/HEAD/tree/trunk/qtfrontend/origin/OpjImporter.cpp
```
