### ISSUE TITLE
Andor's Trail

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#191]
```yaml
meta:
  id: andors_trail
  title: Andor's Trail save
  application: Andor's Trail

doc: | 
  Andor's Trail is an RPG for Android

doc-ref: https://github.com/Zukero/andors-trail/blob/master/AndorsTrail/src/com/gpl/rpg/AndorsTrail/savegames/Savegames.java
```
