### ISSUE TITLE
JVM pack200

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#192]
```yaml
meta:
  id: jvm_pack
  application: 
    - pack200
    - unpack200
  file-extension: pack
  xrefs:
    wikidata: Q1227683
doc: |
  A format to compress JVM JAR files.

doc-ref: https://github.com/netroby/jdk9-dev/blob/master/jdk/src/jdk.pack200/share/native/unpack200/main.cpp
```
