### ISSUE TITLE
Windows Platform Binary Table

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#193]
```yaml
meta:
  id: windows_platform_binary_table
  title: Windows Platform Binary Table
  application: Microsoft Windows

doc: |
  A table in a BIOS containing a PE executable to be executed by Windows. Used by some vendor-preinstalled bacodoors.

doc-ref:
  - https://download.microsoft.com/download/8/A/2/8A2FB72D-9B96-4E2D-A559-4A27CF905A80/windows-platform-binary-table.docx
```
