### ISSUE TITLE
Turi Create SFrame

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#194]
```yaml
meta:
  id: turi_create_sframe
  title: Turi Create SFrame
  application: Turi Create

doc: |
  Turi Create is an external memory machine learning framework. SFrame is an external memory tahle of data similar to pandas.DataFrame

doc-ref: https://github.com/apple/turicreate/blob/master/src/core/storage/sframe_data/sframe_saving.cpp
```
