### ISSUE TITLE
tortoisegit.data

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#195]
```yaml
meta:
  id: tortoisegit_data
  title: tortoisegit.data
  application: TortoiseGit
  xref:
    wikidata: Q178572

doc: |
  TortoiseGit is a GUI frontend for git SCM. It caches some data to tortoisegit.data file in `.git` dir.

doc-ref: https://github.com/TortoiseGit/TortoiseGit/blob/master/src/TortoiseProc/gitlogcache.h
```
