### ISSUE TITLE
com.android.opengl.shaders_cache

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#196]
```yaml
meta:
  id: android_opengl_shaders_cache
  title: com.android.opengl.shaders_cache
  application: Android apps

doc: |
  Android apps using directly or indirectly OpenGL cache something to com.android.opengl.shaders_cache file.

doc-ref:
  - https://android.googlesource.com/platform/frameworks/native/+/master/opengl/libs/EGL/FileBlobCache.cpp
  - https://android.googlesource.com/platform/frameworks/native/+/master/opengl/libs/EGL/BlobCache.cpp
```

```yaml
WiP: https://github.com/kaitai-io/kaitai_struct_formats/blob/shaders_cache/media/android_opengl_shaders_cache.ksy
```
