### ISSUE TITLE
zchunk

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#197]
```yaml
meta:
  id: zchunk
  title: zchunk
  application:
    - unzck
    - zck
    - zckdl
    - zck_read_header
  file-extension: zck
doc: |
  A format for incremental distribution of software updates.

doc-ref: https://github.com/zchunk/zchunk/blob/master/zchunk_format.txt
```
