### ISSUE TITLE
bsdiff

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#198]
```yaml
meta:
  id: bsdiff
  title: bsdiff
  application: bsdiff
  file-extension: bsdiff

doc: |
  a format for diffs of binary files. Used in incremental updates.

doc-ref:
  - https://github.com/mendsley/bsdiff
  - https://github.com/synalysis/Grammars/blob/master/bsdiff.grammar
```
