### ISSUE TITLE
xdelta

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#199]
```yaml
meta:
  id: vcdiff
  title: VCDiff / xdelta
  application: xdelta
  xref:
    rfc: 3284
    wikidata: Q619133

doc: |
  a binary diff format used in incremental updates

doc-ref:
  - https://tools.ietf.org/html/rfc3284
  - https://www.w3.org/TR/NOTE-gdiff-19970901
  - https://github.com/jmacd/xdelta
  - https://github.com/mantlik/xdeltaencoder
```
