### ISSUE TITLE
Windows Prefetch File

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#200]
```yaml
meta:
  id: windows_prefetch_file
  title: Windows Prefetch File 
  application: pf
  file-extension: Microsoft Windows Prefetcher
  xref:
    forensicswiki: Windows_Prefetch_File_Format
    wikidata: Q4047325

doc: |
  Windows Prefetcher service collects info about apps launches to optimize their startup.

doc-ref:
  - https://github.com/libyal/libscca/blob/master/documentation/Windows%20Prefetch%20File%20(PF)%20format.asciidoc
```
