### ISSUE TITLE
Qualcomm Multiple Partition

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#201]
```yaml
meta:
  id: qualcom_mbn
  title: Qualcomm Multiple Partition
  application: Qualcomm SOC
  file-extension: mbn
doc: |
  A format used by Qualcomm SOC to store firmware.

doc-ref:
  - https://github.com/laginimaineb/unpack_bootloader_image/blob/master/unpack_bootloader_image.py
  - https://bits-please.blogspot.ru/2015/08/exploring-qualcomms-trustzone.html
  - https://forum.xda-developers.com/showthread.php?t=2641245
```
