### ISSUE TITLE
Acronis True Image tib

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#202]
```yaml
meta:
  id: acronis_tib
  title: Acronis True Image Backup
  application: Acronis True Image
  file-extension: tib
  xref:
    wikidata: Q2422684

doc: |
  Acronis True Image is a popular backup solution.

doc-ref:
  - https://github.com/cgsecurity/TestDisk/blob/master/src/file_tib.c
  - https://geektimes.ru/post/241086/
```
