### ISSUE TITLE
AutoCAD dwg

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#203]
```yaml
meta:
  id: autocad_dwg
  title: AutoCAD drawing
  application: AutoCAD
  file-extension:
    - dwg
    - dws
    - dwt
  xref:
    justsolve: DWG
    loc: fdd/fdd000445
    pronom:
      fmt: 54
    mime:
      - application/x-dwg
      - image/vnd.dwg
    wikidata: Q1053358

doc: |
  AutoCAD 2D blueprint.

doc-ref:
  - https://github.com/LibreCAD/libdxfrw
  - https://git.savannah.gnu.org/cgit/libredwg.git/tree/
  - https://www.opendesign.com/files/guestdownloads/OpenDesign_Specification_for_.dwg_files.pdf
```
