### ISSUE TITLE
μTP

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#204]
```yaml
meta:
  id: utp
  title: Micro Transport Protocol
  application: Bit-torrent clients
  xref:
    wikidata: Q1063888

doc: |
  A UDP-based Bit-Torrent protocol.

doc-ref:
  - https://www.bittorrent.org/beps/bep_0029.html
```
