### ISSUE TITLE
IDA idb

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#205]
```yaml
meta:
  id: ida_idb
  title: IDA Pro database
  application: IDA Pro
  file-extension:
    - idb
    - i64
  xref:
    wikidata: Q657224

doc: |
  IDA Pro is one of the best software reverse-engineering tools. The database contains the stuff like symbols names mapped to their offsets in the disassembled blob.

doc-ref:
  - https://github.com/nlitsme/idbutil/blob/master/IDB-FORMAT.md
  - https://github.com/williballenthin/python-idb/blob/master/idb/fileformat.py
```
