### ISSUE TITLE
Outlook NK2 Nickfile

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#206]
```yaml
meta:
  id: outlook_nk2
  title: Outlook Nickfile
  application:
    - Outlook
    - NK2Edit
  file-extension: nk2
  xref:
    forensicswiki: Nickfile_(NK2)
    justsolve: Nickfile
  endian: le

doc: |
  A file storing Outlook addressbook.

doc-ref:
  - https://github.com/libyal/libnk2/blob/master/documentation/Nickfile%20(NK2)%20format.asciidoc
  - https://github.com/libyal/libfmapi/blob/master/documentation/MAPI%20definitions.pdf
```
