### ISSUE TITLE
Outlook Personal Folder File / Personal Storage Table

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#207]
```yaml
meta:
  id: outlook_personal_folder_file
  title: Outlook Personal Folder File / Personal Storage Table
  application:
    - Outlook
    - Windows Messagging
  file-extension:
    - pst
    - ost
    - off
    - pab
  xref:
    forensicswiki: Personal_Folder_File_(PAB,_PST,_OST)
    justsolve: Personal_Folder_File
    wikidata: Q1480633

doc: |
  Stores messagges, contacts and calendar.

doc-ref:
  - https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-pst/141923d5-15ab-4ef1-a524-6dce75aae546
  - https://github.com/libyal/libpff/blob/master/documentation/Personal%20Folder%20File%20(PFF)%20format.asciidoc
```
