### ISSUE TITLE
ATA-over-Ethernet

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#208]
```yaml
meta:
  id: ata_over_ethernet
  title: ATA-over-Ethernet
  application:
    - EtherDrive
  xref:
    wikidata:
      - Q298746
      - Q5403289

doc: |
  As the name implyes, this protocol encapsulates ATA commands into Ethernet frames.

doc-ref:
  - http://brantleycoilecompany.com/AoEr11.pdf
  - https://github.com/OpenAoE/aoe
```
