### ISSUE TITLE
glTF

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#209]
```yaml
meta:
  id: gltf
  title: GL Transmission Format, binary container
  file-extension: glb
  xref:
    wikidata: Q28135989

doc: |
  glTF is a format for distribution of 3D models optimized for being used in software

doc-ref:
  - https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#glb-file-format-specification
```
