### ISSUE TITLE
Posit numbers

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#214]
```yaml
meta:
  id: posit
  title: Posit floating point format
  xref:
    wikidata: Q25211958

doc: |
  A new floating point format

doc-ref:
  - https://posithub.org/
  - https://github.com/mightymercado/PySigmoid/blob/master/PySigmoid/Posit.py
```
