### ISSUE TITLE
Add Apple ICNS

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#218]
```yaml
meta:
  id: apple_icns
  title: Apple Icon Image format
  application:
    - Apple MacOS
    - Apple 
  file-extension: icns
  xref:
    justsolve: ICNS
    mime: image/icns
    uti: com.apple.icns
    wikidata: Q2858737

doc: |
  Icons file format used in Apple MacOS.

doc-ref:
  - https://en.wikipedia.org/wiki/Apple_Icon_Image_format
```
