### ISSUE TITLE
Microsoft DXUT sdkmesh

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#219]
```yaml
meta:
  id: dxut_sdkmesh
  title: DXUT Mesh format
  application:
    - Micriosoft DXUT
    - meshconvert
  file-extension: sdkmesh

doc: |
  A 3D model file format used in DXUT (glut analogue for DirectX)

doc-ref:
  - https://github.com/walbourn/contentexporter/wiki/SDKMESH
```
