### ISSUE TITLE
Siemens Voice Memo

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#220]
```yaml
meta:
  id: siemens_vmo
  title: Siemens Voice Memo
  application:
    - Siemens Data Link
  file-extension: vmo
  xref:
    wikidata:
      - Q2532845
      - Q1937936

doc: |
  An ancient file format used in old pre-BENQ Siemens featurephones s.a. SL45 for voice records.

doc-ref:
  - https://github.com/tapwag/siefs/tree/master/converter
```
