### ISSUE TITLE
Huawei EROFS

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#221]
```yaml
meta:
  id: huawei_erofs
  title: Huawei Extendable Read-Only File System
  application: Linux
doc: |
  A read-only filesystem by Huawei.

doc-ref:
  - https://github.com/torvalds/linux/tree/master/drivers/staging/erofs
```
