### ISSUE TITLE
DipTrace Schematics

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#222]
```yaml
meta:
  id: diptrace_dch
  title: DipTrace Schematics
  application: DipTrace
  file-extension: dch
  xref:
    wikidata: Q

doc: |
  A proprietary format for a PCB layout for DipTrace. There is completely no docs or source code samples in the Net. But there are some files :)

doc-ref:
  - https://github.com/briandorey/USB-Smart-Charger-with-BluetoothLE/raw/master/usb%20charger%20-%20bluetooth%201.1.dch
  - https://github.com/rita-gwen/GeigerCounter/raw/master/GeigerSchematics.dch
  - https://codeandlife.com/data/attiny2313_breakout_v2.dch
  - https://cdn.hackaday.io/files/1654057076687520/Game3.dch
  - https://cdn.hackaday.io/files/416721782894848/20140242-3pfc-e-meter-PZ.dch
  - https://cdn.hackaday.io/files/416721782894848/20140242-3pfc-e-meter-PEU-sch.dch
  - https://dixom.ru/index.php?option=com_attachments&task=download&id=19
  - https://www.parallax.com/search?search_api_views_fulltext=diptrace
```
