### ISSUE TITLE
Lightning Memory-mapped DataBase (LMDB)

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#223]
```yaml
meta:
  id: lmdb
  title: Lightning memory-mapped database
  application: LMDB
  xref:
    wikidata: Q20725152

doc: |
  One of the fastest key-value storages.

doc-ref:
  - https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/mdb.c#L4807
```
