### ISSUE TITLE
CLang serialized C++ module AST

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#224]
```yaml
meta:
  id: clang_pcm
  title: CLang serialized C++ module AST
  application: CLang
  file-extension: pcm
  xref:
    wikidata:
      - Q29863318
      - Q864915

doc: |
  C++ has an experimental feature called modules. It is just preparsed and preprocessed AST, not dynamic libraries.

doc-ref:
  - https://github.com/llvm-mirror/clang/blob/master/lib/Serialization/ASTReader.cpp
```
