### ISSUE TITLE
Qt Installer Framework

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#225]
```yaml
meta:
  id: qt_installer_framework
  title: Qt Installer Framework archive
  application: Qt Installer Framework
  file-extension: exe

doc: |
  Qt installer framework is a set of libs to make SFX installers. Instalers usually contain 7zip-compressed archives.

doc-ref:
  - https://github.com/qtproject/installer-framework/blob/master/src/libs/installer/binarycontent.cpp#L111
  - https://github.com/qtproject/installer-framework/blob/master/src/libs/installer/binarycontent.h#L45
```
