### ISSUE TITLE
Qt dockable window saved state

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#227]
```yaml
meta:
  id: qt_dockable_windows_saved_state
  title: Qt dockable window saved state
  application: Qt

doc: |
  Qt is a toolkit for creating GUI applications. It allows saving state of dockable windows, s.a. their positions on screen, sizes, etc.

doc-ref:
  - https://github.com/qt/qtbase/blob/master/src/widgets/widgets/qdockarealayout.cpp#L1874
```
