### ISSUE TITLE
CorelDraw drawing

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#231]
```yaml
meta:
  id: coreldraw_cdr
  title: CorelDraw drawing
  application: CorelDraw
  file-extension: cdr
  xref:
    justsolve: CorelDRAW
    pronom:
     - fmt/465
    wikidata:
      - Q939636
      - Q142371

doc: |
  A native file format of CorelDraw.
  Some test files are available here: https://sourceforge.net/p/uniconvertor/code/HEAD/tree/formats/CDR/test_data/

doc-ref:
  - https://github.com/photopea/CDR-specification
  - https://github.com/LibreOffice/libcdr/tree/master/src/lib
  - https://sourceforge.net/p/uniconvertor/code/HEAD/tree/formats/CDR/docs/specification.txt
  - https://sourceforge.net/p/uniconvertor/code/HEAD/tree/formats/CDR/cdr_explorer/src/
```
