### ISSUE TITLE
PC Screen Font

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#232]
```yaml
meta:
  id: pc_screen_Font 
  title: PC Screen Font
  application:
    - Linux
    - bdf2psf
  file-extension: psf
  xref:
    justsolve: PC_Screen_Font
    mime:
      - application/x-font-linux-psf
    wikidata: Q25098907

doc: |
  A file format used in Linux for virtual console fonts. Sample files are available in packages of various distros.

doc-ref:
  - https://git.kernel.org/pub/scm/linux/kernel/git/legion/kbd.git/tree/src/psf.h
  - https://www.win.tue.nl/~aeb/linux/kbd/font-formats-1.html
  - https://salsa.debian.org/installer-team/console-setup/blob/master/Fonts/bdf2psf
```
