### ISSUE TITLE
RPG Maker 2003

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#236]
```yaml
meta:
  id: rpgmaker_lcf
  title: RPG Maker 2003 lcf
  application: RPG Maker 2003
  file-extension: lcf
  xref:
    wikidata: Q260080

doc: |
  A file format used by RPG Maker and games based on it.

doc-ref:
  - https://github.com/chika-games/RPG-Maker-Specifications
  - https://github.com/EasyRPG/liblcf
```
