### ISSUE TITLE
ZBoxFS

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#237]
```yaml
meta:
  id: zbox_fs
  title: ZboxFS

doc: |
  An embedded encrypted filesystem.

doc-ref:
  - https://github.com/zboxfs/zbox/
```
