### ISSUE TITLE
LittleFS

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#238]
```yaml
meta:
  id: littlefs
  title: LittleFS

doc: |
  A filesystem for microcontrollers with an accent on integrity.

doc-ref:
  - https://github.com/ARMmbed/littlefs
```
