### ISSUE TITLE
Etherium Recursive Length Prefix

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#240]
```yaml
meta:
  id: etherium_rlp
  title: Etherium Recursive Length Prefix
  application:
    - Etherium
    - Etherium Classic

doc: |
  A format used in Etherium to serialise structures of objects.

doc-ref:
  - https://github.com/ethereum/wiki/wiki/RLP#implementations
```
