### ISSUE TITLE
bincode

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#241]
```yaml
meta:
  id: bincode
  title: bincode

doc: |
  A compact binary serialization format used mainly in IPC and RPC.

doc-ref:
  - https://github.com/servo/bincode
```
