### ISSUE TITLE
Flexible Image Transport System

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#242]
```yaml
meta:
  id: nasa_fits
  title: Flexible Image Transport System
  application: 
  file-extension:
    - fits
    - fit
    - fts
  xref:
    fileformat: fits
    justsolve: Flexible_Image_Transport_System
    loc: fdd000317
    mime:
      - image/fits
      - application/fits
    wikidata: Q1428303

doc: |
  A file format mainly used for transfering astronomical data.

doc-ref: 
  - https://fits.gsfc.nasa.gov
```
