### ISSUE TITLE
Flashmap

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#249]
```yaml
meta:
  id: flashpix
  title: Flashpix
  application:
    - Coreboot

doc: | 
  A format describing partitioning of flash memory. Especially small flash memory used for storing firmwares.

doc-ref:
  - https://github.com/dhendrix/flashmap
  - https://doc.coreboot.org/lib/flashmap.html
```

**Comment by trodery** [comment]
I may have this one nearly complete. Will try to look into it further in the coming weeks.

**Comment by GreyCat** [comment]
@trodery Could you share a link to your work in progress, maybe?

**Comment by trodery** [comment]
I used this file to build my definition: https://github.com/dhendrix/flashmap/blob/master/fmap.py

Paying close attention to just:
```
# format string
FMAP_HEADER_FORMAT = "<8sBBQI%dsH" % (FMAP_STRLEN)
FMAP_AREA_FORMAT = "<II%dsH" % (FMAP_STRLEN)
```
Where ```FMAP_STRLEN``` is `32`.

I've never come across flashmap before or use it on a regular basis but putting together this definition did allow for me to start reading the cbfs section of the file.

```
meta:
  id: fmap
  file-extension: fmap
  endian: le

seq:
  - id: fmap
    type: fmap

types:
  fmap:
    seq:
      - id: header
        type: fmap_header
      - id: areas
        type: fmap_area
        repeat: expr
        repeat-expr: header.nareas

  fmap_header:
    seq:
      - id: signature
        contents: "__FMAP__"
      - id: ver_major
        type: u1
      - id: ver_minor
        type: u1
      - id: base
        type: u8
      - id: size
        type: u4
      - id: name
        type: str
        size: 32
        encoding: ASCII
      - id: nareas
        type: u2

  fmap_area:
    seq:
      # Where area starts (relative to base in fmap header).
      - id: offset
        type: u4
      - id: size
        type: u4
      - id: name
        type: str
        size: 32
        encoding: ASCII
      - id: flags
        type: u2
        enum: flags
    enums:
      flags:
        0: fmap_area_static
        1: fmap_area_compressed
    # instances:
    #   data:
    #     pos: offset
    # I believe repeating cbfs components go here?
```

Please critique or make any suggestions.

**Comment by KOLANICH** [comment]
1. make a PR
2. `version` fields should be grouped in a struct
3. `ASCII` should be lower case. Also please check if it is really ascii. All modern stuff usually uses utf-8 for a 1-byte encoding for ASCII chars, so non-ascii is also welcome.
4.  `flags` should be a type of bit fields rather than a enum

**Comment by generalmimon** [comment]
> 3\. `ASCII` should be lower case.

I don't think so, in both [KSY reference](https://doc.kaitai.io/ksy_reference.html#meta-encoding) and [user guide](https://doc.kaitai.io/user_guide.html#_fixed_size_structures) occur only upper case `encoding` values (`UTF-8`, `ASCII` etc., not `ascii`).

**Comment by trodery** [comment]
> 1. make a PR
> 2. `version` fields should be grouped in a struct
Can you provide an example I can mimic?
> 3. `ASCII` should be lower case.
Ok, no problem. I probably used `ASCII` because I saw it used in another definition
> 4. it probably should be in `meta`
What should be in `meta`?
> 5. Also please check if it is really ascii. All modern stuff usually uses utf-8, which is compatible to ascii for ascii stuff.
The code I referenced is python2 which, IIRC, needed to prepend `u` to unicode strings thus making everything ascii by default.
> 6. `flags` should be a type of bit fields rather than a enum
Could use an example for this as well.

**Comment by KOLANICH** [comment]
2.
```yaml
....
version:
  seq:
    - id: major
      type: u1
    - id: minor
      type: u1
  fmap_header:
    seq:
      - id: signature
        contents: "__FMAP__"
     - id: version
       type: version
....
```

4. 
```yaml
encoding: ascii
```

6.
```yaml
flags:
  seq: # 2 bytes int, little endian, that's why it is split 
    - id: reserved0
      type: b4
    - id: ro
      type: b1
    - id: compressed
      type: b1
    - id: static
      type: b1
    - id: preserve
      type: b1
    - id: reserved1
      type: u1
```
