### ISSUE TITLE
Coreboot payload interface tables

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#250]
```yaml
meta:
  id: coreboot_tables
  title: Coreboot payload interface tables
  application:
    - Coreboot
    - libpayload
  license: BSD-3-Clause

doc: |
  Various tables used by coreboot for exposing various information to payloads and OSes

doc-ref:
  - https://github.com/coreboot/coreboot/blob/master/payloads/libpayload/include/coreboot_tables.h
  - https://github.com/coreboot/coreboot/blob/master/src/commonlib/include/commonlib/coreboot_tables.h
```
