### ISSUE TITLE
BCD implementation doesn't yield expected results

### ISSUE THREAD

**Issue by ajorg** [kaitai-io/kaitai_struct_formats#251]
I was trying to use Kaitai to build a parser for the data format of a radio config file. In part of the file there are frequencies encoded as binary-coded decimal. I've parsed the same data using [`chirp/bitwise.py`](https://chirp.danplanet.com/projects/chirp/repository/entry/chirp/bitwise.py), which is also used to parse tens of other, similar data files.

The hex of the data being parsed is:

```
0x80    00 04 70 04 36 01 74 01
````

In the CHIRP bitwise dsl I'm using:

```c
#seekto 0x80;
lbcd loweruhf[2];
lbcd upperuhf[2];
lbcd lowervhf[2];
lbcd uppervhf[2];
```

(`lbcd` meaning little-endian BCD)
This correctly yields:

```
         loweruhf: 2:[(400)]
         upperuhf: 2:[(470)]
         lowervhf: 2:[(136)]
         uppervhf: 2:[(174)]
```

I expected to be able to parse the same data in Katai using:

```yaml
meta:
  id: gd77
  file-extension: dat
  imports:
   - /bcd
seq:
  - id: skip
    size: 128
  - id: loweruhf
    type: bcd(4, 4, true)
  - id: upperuhf
    type: bcd(4, 4, true)
  - id: lowervhf
    type: bcd(4, 4, true)
  - id: uppervhf
    type: bcd(4, 4, true)
```

But instead of getting the same values as the above, I'm getting `4000`, `4007`, `1063`, and `1047`.
If I do the obvious thing and pass `false` into the `bcd` parser instead of `true`, I get `0004`, `7004`, `3601`, and `7401`. There seems to be no way to get the correct values from this parser.

I'm open to the possibility that the CHIRP lbcd parser is wrong, except that it's right for every data file it parses, and there are 41 file formats that it correctly parses with its lbcd parser.

Am I using the bcd parser wrong? There are 4 digits, there are 4 bits per digit, and neither endian is yielding the correct result.

**Comment by ajorg** [comment]
I found in https://github.com/kaitai-io/kaitai_struct/issues/78 examples that lead me to be able to write a type that works for the format I'm using:

```yaml
types:
  lbcd4:
    seq:
      - id: digits
        type: b4
        repeat: expr
        repeat-expr: 4
    instances:
      as_int:
        value: >
          digits[1] +
          digits[0] * 10 +
          digits[3] * 100 +
          digits[2] * 1000
```

I gather from that discussion that possibly there just needs to be another parameter to `/common/bcd` but that it would be needlessly complicated to support it in the library as there seem to be lots of ways to do BCD.

If it's possible to add another parameter that would order the bytes the way I needed, that would be cool, but I've got what I need for now.
