### ISSUE TITLE
Signed version of vlq_base128?

### ISSUE THREAD

**Issue by pedronavf** [kaitai-io/kaitai_struct_formats#252]
I'm trying to add support for signed integer values to vlq_base128_le but I'm not sure how to do it. 

Signed values are the same as unsigned but the last byte has a sign in bit 6. The pseudocode according to wikipedia is:

```c
result = 0;
shift = 0;

/* the size in bits of the result variable, e.g., 64 if result's type is int64_t */
size = number of bits in signed integer;

do {
  byte = next byte in input;
  result |= (low order 7 bits of byte << shift);
  shift += 7;
} while(high order bit of byte != 0);

/* sign bit of byte is second high order bit (0x40) */
if ((shift <size) && (sign bit of byte is set))
  /* sign extend */
  result |= (~0 << shift);
```
The current vlq_base128 implementation takes care of the first `do...while` but I'm not sure how to add the `if`block to the `value` instance's expression, especially since it's the last byte. I can add an `is_negative` instance that tells me if the last byte has a sign:

```yaml
instances:
  len:
    value: groups.size
  value:
    value: >-
      groups[0].value
      + (len >= 2 ? (groups[1].value << 7) : 0)
      + (len >= 3 ? (groups[2].value << 14) : 0)
      + (len >= 4 ? (groups[3].value << 21) : 0)
      + (len >= 5 ? (groups[4].value << 28) : 0)
      + (len >= 6 ? (groups[5].value << 35) : 0)
      + (len >= 7 ? (groups[6].value << 42) : 0)
      + (len >= 8 ? (groups[7].value << 49) : 0)
    doc: Resulting value as normal integer
  is_negative:
    value: groups[len-1].value & 0b0100_0000 != 0
```

But I don't know what to do with the information and how can I change the `value` instance to modify its last bite or how to add another statement to the `value` expression.

**Comment by GreyCat** [comment]
First of all, I'd recommend:

```yaml
  is_negative:
    value: groups.last.value & 0b0100_0000 != 0
```

For application of the negative sign, it might be using the same ternary operation:

```yaml
  signed_value:
    value: 'is_negative ? -value: value`
```

**Comment by pedronavf** [comment]
Ah, good thing about the last property.

The problem is that if the last byte is negative it's not enough with making the whole number negative, the last byte needs to change as it's a two's complement. For example, if `-1` is encoded we get with `0x7f` which is `127`, if we make it negative we get `-127`.

So if `is_negative` is true we would need to perform that operation on the last byte. In all implementations I've seen they do an additional `if` check after calculating the value. Is it possible to add another expression to `value`?

```yaml
value: >-
      groups[0].value
      + (len >= 2 ? (groups[1].value << 7) : 0)
      + (len >= 3 ? (groups[2].value << 14) : 0)
      + (len >= 4 ? (groups[3].value << 21) : 0)
      + (len >= 5 ? (groups[4].value << 28) : 0)
      + (len >= 6 ? (groups[5].value << 35) : 0)
      + (len >= 7 ? (groups[6].value << 42) : 0)
      + (len >= 8 ? (groups[7].value << 49) : 0)
       <do if_check and flip the bits here ? >
```

Or do we need to use an intermediate instance and somehow operate on the last byte returned in `value`?

**Comment by GreyCat** [comment]
Ternary operation *is* the "if" check, if you want two alternatives for both true and false: `condition ? value_if_true : value_if_false`. Another option would be to use `if: condition` clause, but that implies only one outcome and null otherwise.

**Comment by GreyCat** [comment]
Also, it might help to use `~value` instead of `-value`, if I've understood you correctly.

**Comment by pedronavf** [comment]
I think we need to apply `~` to the last byte, so we might need to extend the expression to something like this:
```yaml
value: >-
     (len < 2 ? is_negative: ~groups[0].value : groups[0].value)
      + (len >= 2 ? (is_negative? ~groups[1].value << 7 : groups[1].value << 7) : 0)
      + (len >= 3 ? (is_negative? ~groups[2].value << 14 : groups[2].value << 14) : 0)
     <etc...>
```
Or maybe `value` could be used in another instance but then we would need to undo the addition of the last byte so we can add it again after calculating the two's complement. A naive implementation could be:

```yaml
instances:
  value:
    value: >-
       groups[0].value
        + (len >= 3 ? (groups[2].value << 14) : 0)
       (...etc...)

  signed:
    value: >-
      is_negative? (value - (groups[len -1].value << 7 * (len - 1)) + (~groups[len-1].value) : value)
```
I haven't actually wrote code to decode a Signed LEB128, I think I need to do it so I can have a better grasp of what's involved with all that bit manipulation, but am I on the right path? Can Kaitai's expression have more than one statement?

Thanks for all the help so far
