### ISSUE TITLE
Xilinx FPGA bitstream

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#255]
```yaml
meta:
  id: xilinx_bitstream
  title: Xilinx FPGA Bitstream
  license: Apache-2.0
endian: be
```
```yaml
WiP: https://github.com/SymbiFlow/prjxray/blob/fa162e0b54d1d3a01e915012f7c71881c23c0b88/docs/xilinx_bitstream.ksy
```

Implemented by @kc8apf and @mithro but was removed in https://github.com/SymbiFlow/prjxray/commit/a6f1e92ee67cb73207e186e10e357e690b8fbba9 .
