### ISSUE TITLE
Racket bytecode

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#260]
```yaml
meta:
  id: racket_zo
  title: Racket bytecode
  application:
    - raco
  file-extension: zo
  xref:
    wikidata: Q1254148

doc: |
  Racket source can be compiled into bytecode.

doc-ref:
  - https://docs.racket-lang.org/raco/decompile.html
  - https://github.com/racket/racket/blob/master/pkgs/zo-lib/compiler/
  - https://github.com/racket/racket/wiki/Inside-Racket-Seminar-2.-Matthew-Flatt-on-Bytecode-Compiler
```
