### ISSUE TITLE
MoarVM Bytecode

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#270]
```yaml
meta:
  id: moarvm_bytecode
  title: Metamodel On A Runtime VM (MoarVM) bytecode
  application: MoarVM
  file-extension: moarvm
  xref:
    wikidata: Q16948420

doc: |
  Bytecode for MoarVM, that is used in Raku (formerly Perl 6) programming language.

doc-ref:
  - https://github.com/MoarVM/MoarVM/blob/master/docs/bytecode.markdown
```
