### ISSUE TITLE
Apache JServ Protocol

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#271]
```yaml
meta:
  id: apache_jserv
  title: Apache JServ Protocol
  application:
    - Apache Tomcat
    - Apache HTTPD mod_jk
    - Undertow
  xref:
    wikidata: Q616890

doc: |
  A protocol for interaction to some JVM-based web servers.

doc-ref:
  - https://tomcat.apache.org/connectors-doc/ajp/ajpv13a.html
```
