### ISSUE TITLE
Apple icon image (ICNS)

### ISSUE THREAD

**Issue by dgelessus** [kaitai-io/kaitai_struct_formats#307]
```yaml
meta:
  id: apple_icns
  title: Apple icon image (ICNS)
  application:
    # Listing only official Apple software.
    # Various third-party software also supports reading and writing the format.
    - macOS
    - Preview (macOS)
    - icns Browser
    - Icon Composer
    - iconutil
  file-extension: icns
  xref:
    justsolve: ICNS
    mime: image/icns
    pronom: fmt/1185
    wikidata: Q2858737
doc: |
  Icon image format used by Mac OS 8.5 and later,
  including all versions of Mac OS X/macOS.
  This is the Mac equivalent of the Windows ICO format.

  An ICNS file stores an *icon family*:
  a collection of images with visually the same content,
  but at different resolutions and color depths.
  When the system renders an icon on screen,
  it chooses the most optimal format from the icon family to display to the user,
  depending on the icon's displayed size and the capabilities of the display hardware.

  An icon family in an ICNS file can also contain other nested icon families.
  This feature is sometimes used to represent different states or visual variants of the same icon,
  such as an opened, selected or dark mode version.

  Each icon in an icon family is identified by a four-byte type code,
  which also indicates the image data format and resolution.
  Supported formats include PNG and JPEG 2000 (for larger sizes and modern systems)
  and multiple raw bitmap formats with varying resolution, color depth, and transparency support
  (for smaller sizes and/or compatibility with older systems).

  ICNS data is sometimes stored in resource forks as resources of type `'icns'`.
  This was especially common in Classic Mac OS and Carbon applications,
  and is still used on modern macOS versions to store custom file and folder icons.
doc-ref:
  - 'https://sourceforge.net/p/icns/ libicns SourceForge project'
  - 'https://github.com/python-pillow/Pillow/blob/master/src/PIL/IcnsImagePlugin.py Python Pillow ICNS plugin code'
  - "https://www.macdisk.com/maciconen.php#icns Information about 'icns' resources in resource forks"
```

I'm working on a spec for the format and will make a PR when it's ready.
