### ISSUE TITLE
[WIP] Bluetooth frame in PCAP (network)

### ISSUE THREAD

**Issue by ildar** [kaitai-io/kaitai_struct_formats#321]
``` yaml
meta:
  id: bluetooth_frame
  title: Bluetooth frame (layer 2, IEEE 802.15.1)
  xref:
    ieee: 802.15.1
  license: CC0-1.0
doc: |
  Bluetooth frame is a OSI data link layer (layer 2) and higher protocol data
  unit for Bluetooth networks.
doc-ref: https://www.bluetooth.org/docman/handlers/downloaddoc.ashx?doc_id=457080
```

[Source](https://github.com/ildar/kaitai_struct_formats/blob/master/network/bluetooth_frame.ksy)
