### ISSUE TITLE
Qualcomm Calibration Network

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#324]
```yaml
meta:
  id: qualcomm_calibration_network
  title: Qualcomm Calibration Network
  application:
    - Qualcomm chips
    - qfil
    - QPST
  file-extension: qcn
  xref:
    wikidata: Q544847

doc: |
  File format used by Qualcomm ch9ps to store information related to modem operation
  Sample files can be downloaded here: https://github.com/samunlock/QCN_FILE

doc-ref:
  - https://github.com/dl12345/qcn/blob/master/qcn.hpp
  - Bunch of links on XDA
```
