### ISSUE TITLE
Gatan Digital Micrograph

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#325]
```yaml
meta:
  id: gatan_dm
  title: Gatan Digital Micrograph
  application: Gatan Microscopy Suite
  file-extension:
    - dm2
    - dm3
    - dm4
  xref:
    justsolve:
      - DM2
      - DM3
    pronom: 
     - x-fmt/1131

doc: |
  A file format for transmission electron microscopy.

doc-ref:
  - https://www.ntu.edu.sg/home/cbb/info/dmformat/index.html
  - https://imagej.nih.gov/ij/plugins/DM3Format.gj.html
  - https://github.com/openmicroscopy/bioformats/blob/develop/components/formats-gpl/src/loci/formats/in/GatanReader.java
  - https://github.com/openmicroscopy/bioformats/blob/develop/components/formats-gpl/src/loci/formats/in/GatanDM2Reader.java
```
