### ISSUE TITLE
Inno Setup

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#326]
```yaml
meta:
  id: inno_setup
  title: Inno Setup installer
  application: Inno Setup
  file-extension: exe
  xref:
    wikidata: Q744702

doc: |
  Data structure within InnoSetup installers.

doc-ref:
  - https://github.com/jrsoftware/issrc
  - https://github.com/dscharrer/innoextract
```
