### ISSUE TITLE
Install Shield bytecode format version ≥ 6

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#327]
```yaml
meta:
  id: install_shield_bytecode_v6
  title: Install Shield bytecode format version ≥ 6
  application:
    - Install Shield v. 
  file-extension:
    - inx
  xref:
    pronom:
     - fmt/197
    wikidata: Q1193296

doc: |
  A format used by InstallShield installers to store the scripts to execute.
  Some versions of bytecode may be obfuscated using a simple scheme, to deobfuscate use the following pseudocode: (credited to user dmit of exetools (IDK if it was reversed by him, or someone else), https://forum.exetools.com/showpost.php?p=31309&postcount=2):
    tmp = inByte ^ 0xF1
    outByte = ((tmp >> 2) | (tmp << 6)) - (_index % 71)

doc-ref:
  - https://docs.revenera.com/eol/installshield.htm
  - https://github.com/darknesswind/IsDcc
  - https://forum.exetools.com/showthread.php?t=6444  # some info on obfuscation + ISDHelper  + ISDGoBack sources
  - https://forum.exetools.com/showthread.php?t=12708
  - sid by sn00pee
```
