### ISSUE TITLE
InstallShield archive format version 3

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#328]
```yaml
meta:
  id: install_shield_archive_v3
  title: InstallShield archive format version 3
  application:
    - InstallShield (very old versions)
  file-extension:
    - Z
  xref:
    justsolve:
      - InstallShield_Z 
    wikidata: Q1193296

doc: |
  A very old format used by InstallShield installers usually from 199x.
  This version uses the compression implemented in https://github.com/madler/zlib/tree/master/contrib/blast

doc-ref:
  - https://docs.revenera.com/eol/installshield.htm
  - https://www.sac.sk/download/pack/icomp95.zip # i3comp
  - https://github.com/DeclanHoare/stix
  - https://github.com/putara/isdecomp # !!!
  - https://github.com/lephilousophe/idecomp
  - https://github.com/wfr/unshieldv3
  - https://github.com/OmniBlade/isextract
  - https://github.com/agrif/unshield # rust
```
