### ISSUE TITLE
InstallShield archive format version ≥4

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#329]
```yaml
meta:
  id: install_shield_archive_v4
  title: InstallShield archive format version ≥4
  application:
    - InstallShield
  file-extension:
    - exe
    - cab # v5, v6
    - hdr # v6
  xref:
    justsolve:
      - InstallShield_installer_archive  # ??_
      - InstallShield_CAB
    wikidata: Q1193296

doc: |
  A format used by InstallShield installers from late 199x to 200x. v4 format version contains nothing to autodetect it.

doc-ref:
  - https://www.sac.sk/download/pack/i5comp21.rar # v5
  - https://www.sac.sk/download/pack/i6cmp13b.zip # i6comp (v6)
  - https://github.com/hifi/iss_extract # v6
  - https://github.com/twogood/unshield # (v5+)
  - https://github.com/lifenjoiner/ISx # (DevStudio 9 (2003) to InstallShield 2016, also may work on InstallShield = 4 by providing /VERSION flag )
  - https://web.archive.org/web/20140910014300/http://forum.exetools.com/showthread.php?t=3619 # i705unpack.rar (v7, may also contain IsXunpack)
  - https://github.com/REGoth-project/CAB-Installer-Extractor
  - https://github.com/FauxFaux/deshield # java
  - https://plugring.farmanager.com/plugin.php?pid=512&l=en # (version not documented, maybe I should move it to 3)
```
