### ISSUE TITLE
SAPIEN Script Packager

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#330]
```yaml
meta:
  id: sapien_script_packager
  title: SAPIEN Script Packager
  application:
    - SAPIEN Script Packager
    - PowerShell Studio
    - PrimalScript
  file-extension: exe
  license: Unlicense

doc: |
  SAPIEN Script Packager packages PowerShell scripts as exes.

doc-ref:
  - https://github.com/dfir-it/unsapien/blob/master/unsapien.py # implemented in Construct
  - https://www.exploit-monday.com/2012/05/extracting-hard-coded-credentials-using.html
  - https://www.remkoweijnen.nl/blog/2017/03/13/convert-executable-powershell/
```
