### ISSUE TITLE
Tomb Raider I-V level

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#331]
```yaml
meta:
  id: tomb_raider_level
  title: Tomb Raider I-V level
  application:
    - early Tomb Raider games
    - OpenTomb
    - OpenLara
  file-extension:
    - phd # 1
    - tub # 1 UB
    - tr2 # 2, 3
    - tr4 # The Last Revelation
    - trc # Chronicles
  xref:
    wikidata:
      - Q317620
      - Q816451
      - Q1123794
      - Q668568
      - Q642359

doc: |
  Levels of  Tomb Raider games

doc-ref:
  - https://github.com/XProger/OpenLara # BSD license
  - https://github.com/opentomb/OpenTomb/blob/master/src/vt/l_main.cpp#L179
  - https://github.com/opentomb/OpenTomb/blob/dee5090c0636ef25138a1908ea4a817e2da66b5c/src/vt/vt_level.cpp#L40
  - https://github.com/opentomb/OpenTomb/blob/dee5090c0636ef25138a1908ea4a817e2da66b5c/src/vt/l_tr1.cpp#L620
  - https://github.com/opentomb/OpenTomb/blob/dee5090c0636ef25138a1908ea4a817e2da66b5c/src/vt/l_tr2.cpp#L242
  - https://github.com/opentomb/OpenTomb/blob/dee5090c0636ef25138a1908ea4a817e2da66b5c/src/vt/l_tr3.cpp#L191
  - https://github.com/opentomb/OpenTomb/blob/dee5090c0636ef25138a1908ea4a817e2da66b5c/src/vt/l_tr4.cpp#L334
  - https://github.com/opentomb/OpenTomb/blob/dee5090c0636ef25138a1908ea4a817e2da66b5c/src/vt/l_tr5.cpp#L412
```
