### ISSUE TITLE
Tomb Raider I-V sound

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#332]
```yaml
meta:
  id: tomb_raider_sound
  title: Tomb Raider I-V sound
  application:
    - early Tomb Raider games
    - OpenTomb
    - OpenLara
  file-extension: wad
  xref:
    wikidata:
      - Q317620
      - Q816451
      - Q1123794
      - Q668568
      - Q642359

doc: |
  Sounds of Tomb Raider games

doc-ref:
  - https://github.com/XProger/OpenLara/blob/9e904600a647027100f2cd7d769847f708d90368/src/sound.h#L1138
  - https://github.com/opentomb/OpenTomb/blob/master/src/audio/audio.cpp#L279
```
