### ISSUE TITLE
Keepass KDBX

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#333]
```yaml
meta:
  id: keepass_kdbx
  title: Keepass KDBX XML
  application:
    - Keepass 2
    - KeepassX
    - KeepassXC
    - KeePassDroid
  file-extension: kdbx 
  xref:
    #rfc: # TBD, see rfc.txt in doc-ref
    wikidata:
      - Q762660
      - Q4042120
      - Q28974968

doc: |
  Keepass password database

doc-ref:
  - https://github.com/keepassxreboot/keepassxc-specs/blob/master/kdbx-xml/rfc.txt
  - https://keepass.info/help/kb/kdbx_4.html
  - https://gist.github.com/lgg/e6ccc6e212d18dd2ecd8a8c116fb1e45
  - https://gist.github.com/msmuenchen/9318327
  - https://github.com/keepassx/keepassx/tree/master/src/format
  - https://github.com/libkeepass/pykeepass/tree/master/pykeepass/kdbx_parsing
  - https://github.com/cternes/openkeepass
```

```yaml
WiP:
  - https://gist.github.com/Alex131089/a078613c7336d93441f9c622785eb29f
```
