### ISSUE TITLE
Keepass KDB

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#334]
```yaml
meta:
  id: keepass_kdb
  title: Keepass KDB
  application:
    - Keepass 2
    - KeepassX
    - KeepassXC
    - KeePassDroid
  file-extension: kdb
  xref:
    wikidata:
      - Q762660
      - Q4042120
      - Q28974968

doc: |
  Keepass password database

doc-ref:
  - https://sourceforge.net/projects/keepass/files/KeePass%202.x/2.37/KeePass-2.37-Source.zip/download
  - https://gist.github.com/lgg/e6ccc6e212d18dd2ecd8a8c116fb1e45
  - https://github.com/keepassx/keepassx/tree/master/src/format
  - https://github.com/libkeepass/pykeepass/tree/master/pykeepass/kdbx_parsing
  - https://github.com/cternes/openkeepass
```
