### ISSUE TITLE
Windows Animated Cursor

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#336]
```yaml
meta:
  id: animated_cursor_windows
  title: Microsoft Windows Animated cursor
  application: Microsoft Windows
  file-extension: ani
  xref:
    fileformat: # https://www.fileformat.info
    justsolve: Windows_Animated_Cursor
    pronom: fmt/386
    wikidata: Q295711
  imports:
    - /common/riff

doc: |
  Animated cursor used in Windows

doc-ref:
  - https://www.gdgsoft.com/anituner/help/aniformat.htm
  - https://github.com/jsummers/deark/blob/0a419c9141543433357c36a878e7917ce4a317ca/modules/riff.c#L456
  - https://github.com/wine-mirror/wine/blob/96a6053feda4e16480c21d01b3688a8d38e5ad6d/dlls/user32/cursoricon.c#L1393
```
