### ISSUE TITLE
D-Bus pcap frame

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#337]
```yaml
meta:
  id: pcap_dbus
  title: D-Bus pcap frame
  application: dbus-dump
  file-extension: pcap
  xref:
    wikidata: Q768923

doc: |
  Pcap frame format for dumping D-Bus messages.

doc-ref:
  - https://github.com/mvidner/dbus-dump/blob/master/lib/pcap/savefile.rb
```
