### ISSUE TITLE
LightGBM model

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#338]
```yaml
meta:
  id: lightgbm_model
  title: LightGBM model
  application: LightGBM
  file-extension: 
  xref:
    wikidata: Q99515298

doc: |
  LightGBM is a gradient-boosted decision tree (ahd other models too) macuine learning library by Microsoft

doc-ref:
  - https://github.com/Microsoft/LightGBM/blob/f7ad945717d90a47f68dcac78ebc508a1fe00c40/src/io/dataset.cpp#L902
```
