### ISSUE TITLE
APKMirror proprietary format

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#354]
```yaml
meta:
  id: apkmirror_apkm
  title: APKMirror proprietary format
  application:
    - unapkm
    - APKMirror Installer
  file-extension: apkm

doc: | 
  APKMirror has introduced a proprietary format in order to force users to use their app with ads.

doc-ref:
  - https://github.com/MuntashirAkon/unapkm-android/blob/master/app/src/main/java/com/souramoo/unapkm/UnApkm.java
  - https://github.com/souramoo/unapkm/blob/master/src/main/java/com/souramoo/unapkm/UnApkm.java
  - https://github.com/android-police/apkmirror-public/issues/113
```
