### ISSUE TITLE
IVUE/FlashPix file format

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#362]
```yaml
meta:
  id: ivue_flashfix
  title: IVUE/FlashPix file format
  file-extension:
    - ivue
    - fpx
  xref:
    justsolve: FlashPix
    mmwiki: FlashPix
    mime: image/vnd.fpx
    wikidata: Q371784

  imports:
    - /serialization/microsoft_cfb

doc: | 
  An ancient image format that was planned to be a part of WWW, but now is used usually as graphics embedded into MS Word documents.

doc-ref:
  - https://www.w3.org/Graphics/FlashPix/FPX-spec.pdf
  - http://graphcomp.com/info/specs/livepicture/fpx.pdf
  - https://www.w3.org/Graphics/FlashPix/IIPv1.0r11.pdf
```
