### ISSUE TITLE
Info-Tech Storage Format / Microsoft Compiled HTML Help

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#363]
```yaml
meta:
  id: microsoft_itsf
  title: Info-Tech Storage Format / Microsoft Compiled HTML Help
  application: 
    - Microsoft HTML Help Executable
    - Microsoft's HTML Help Workshop and Compiler
    - Microsoft Reader
    # and lots of other by third parties
  file-extension:
    - chm
    - chi
    - chq
    - chw
    - kpd
    - lit
  xref:
    justsolve: CHM
    mime: application/vnd.ms-htmlhelp
    wikidata: Q1023647

doc: |
  "New" (old ones are hlp) help files for Windows use this format.

doc-ref:
  - https://github.com/kovidgoyal/calibre/search?q=lit
  - https://github.com/jedwing/CHMLib
  - http://www.russotto.net/chm/chmformat.html
  - https://github.com/dottedmag/archmage
```

```yaml
WiP:
  - 
issues:
  block: [ ]
  affect: [ ]
```
