### ISSUE TITLE
Microsoft Cabinet

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#364]
```yaml
meta:
  id: microsoft_cab
  title: Microsoft Cabinet
  application:
    - Microsoft Windows
    - 7Zip
  file-extension: cab
  xref:
    forensicswiki: Cabinet Archive Format (CAB)
    fileformat: cab
    justsolve: Ext:cab
    mime: application/vnd.ms-cab-compressed
    uti: public.archive.cab
    wikidata: Q194831
  imports:
    - /serialization/microsoft_cfb

doc: |
  A Microsoft format of archives used as a base for their packages, such as installers and updates.

doc-ref:
  - https://download.microsoft.com/download/4/d/a/4da14f27-b4ef-4170-a6e6-5b1ef85b1baa/%5Bms-cab%5D.pdf
  - https://github.com/kyz/libmspack
```
