### ISSUE TITLE
Microsoft Installer Package

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#365]
```yaml
meta:
  id: microsoft_msi
  title: Microsoft Installer Package
  application:
    - Windows Installer
    - msitools
    - lessmsi
  file-extension:
    - msi
    - msp
  xref:
    wikidata: Q181233
  imports:
    - /archives/microsoft_cab

doc: |
  Microsoft (Windows) Installer is a kind of a native package manager for Windows, but it is very primitive and supports no dependencies tracking (if one needs something smarter, he has to use it via its API with the logic implemented in an own process).

doc-ref:
  - https://github.com/activescott/lessmsi
  - https://gitlab.gnome.org/GNOME/msitools
  - https://github.com/wine-mirror/wine/tree/master/dlls/msi
```
