### ISSUE TITLE
COM / OLE Type Library

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#366]
```yaml
meta:
  id: com_type_library
  title: COM / OLE Type Library
  application:
    - Microsoft COM
    - Wine
    - MIDL
    - WIDL
    - Microsoft OLEView
    # and lot of third-party apps and libs
  file-extension: tlb
  xref:
    wikidata: Q662200
  includes:
    - /serialization/microsoft_cfb

doc: |
  COM Type library contain some serialized data from IDLs that can be quite easily consumed by software. The data can be deserialized back into IDLs.
  Sample files can be found in tools repos. Or in Wine or Windows distros and SDKs. Or compiled yourself with WIDL.

doc-ref:
  - https://docs.microsoft.com/en-us/windows/win32/midl/com-dcom-and-type-libraries
  - https://docs.microsoft.com/en-us/previous-versions/windows/desktop/automat/contents-of-a-type-library
  - https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-loadtypelib
  - https://github.com/dewhisna/TLBTools
  - https://github.com/Feb30th/TypeLibParser
  - https://github.com/wine-mirror/wine/blob/master/tools/winedump/tlb.c
  - https://github.com/wine-mirror/wine/blob/master/tools/widl/typelib.c
```
