### ISSUE TITLE
Masseffect 2 / 3 save

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#367]
```yaml
meta:
  id: masseffect_save
  title: Masseffect 2 / 3 save
  application:
    - Mass Effect 2
    - Mass Effect 3
  file-extension: 
  xref:
    wikidata:
      - Q725057
      - Q753511

doc: |
  Mass Effect is a series of videogames by BioWare. The games are series and RPG and one can import a save of a previous version of a game (AND DLCs) into a next one to get the story altered by the decisions done in previous versions instead of getting "resetted" default ones.

doc-ref:
  - https://github.com/EmperorArthur/MassEffect2-SaveEditor
```
