### ISSUE TITLE
CatBoost model

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#368]
```yaml
meta:
  id: catboost_model
  title: Yandex CatBoost model
  application: CatBoost
  file-extension: 

doc: |
  CatBoost is a library implementing gradient boosted decision trees.

doc-ref:
  - https://github.com/catboost/catboost/blob/master/catboost/libs/model/model.cpp#L319
```
