### ISSUE TITLE
Blizzard Mike O'brien PaCK

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#369]
```yaml
meta:
  id: blizzard_mpq
  title: Blizzard Mike O'brien PaCK
  application: Blizzard games
  file-extension: mpq

doc: |
  File format used by Blizzard games to store resources upon which other formats are built.

doc-ref:
  - http://www.zezula.net/en/mpq/main.html
  - https://github.com/ladislav-zezula/StormLib
  - https://github.com/icza/mpq
```
