### ISSUE TITLE
Intel CPU microcode

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#370]
```yaml
meta:
  id: intel_x86_microocde
  title: Intel CPU microcode
  application: Intel CPU
  xref:
    wikidata: Q175869

doc: |
  Modern CPUs are really RISC and have some complex instructions implemented via microcode.

doc-ref:
  - https://github.com/ddcc/microparse
```
