### ISSUE TITLE
AMD CPU microcode

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#371]
```yaml
meta:
  id: amd_x86_microocde
  title: AMD CPU microcode
  application: AMD CPU
  xref:
    wikidata: Q175869

doc: |
  Modern CPUs are really RISC and have some complex instructions implemented via microcode.

doc-ref:
  - https://github.com/ddcc/microparse
```
