### ISSUE TITLE
VIA CPU microcode

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#372]
```yaml
meta:
  id: via_x86_microocde
  title: VIA CPU microcode
  application: VIA CPU
  xref:
    wikidata: Q175869

doc: |
  Modern CPUs are really RISC and have some complex instructions implemented via microcode.

doc-ref:
  - https://github.com/ddcc/microparse
```
