### ISSUE TITLE
AMD GPU BIOS

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#373]
```yaml
meta:
  id: amd_gpu_atom_bios
  title: AMD GPU BIOS
  application:
    - AMD GPU
    - atombios

doc: |
  AMD GPU BIOSes have a modular structure. They are not just a blob of machine code.

doc-ref:
  - https://cgit.freedesktop.org/~mhopf/AtomDis/tree/
```
