### ISSUE TITLE
Intel Management Engine firmware

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#374]
```yaml
meta:
  id: intel_me
  title: Intel Management Engine firmware
  application: Intel ME
  xref:
    wikidata: Q42915608

doc: |
  Intel ME is a non-user-controled CPU within a CPU/chipset. And its firmware has a certain structure.

doc-ref:
  - https://github.com/platomav/MEAnalyzer/blob/master/MEA.py
```
