### ISSUE TITLE
UnQLite database

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#375]
```yaml
meta:
  id: unqlite_db
  title: UnQLite database
  application: UnQLite
  file-extension: db

doc: |
  UnQLite is an embedded NoSQL database.

doc-ref:
  - https://github.com/symisc/unqlite/blob/master/src/pager.c
```
