### ISSUE TITLE
Holux gm-100 GPS Waypoints

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#377]
```yaml
meta:
  id: holux_gps_wpo
  title: Holux gm-100 GPS Waypoints
  application:
    - Holux GPS receivers
  file-extension: wpo
doc: |
  Waypoints format used in Holux gm-100 GPS receivers.
  Test-data https://github.com/gpsbabel/gpsbabel/blob/master/reference/holux.wpo

doc-ref:
  - https://www.gpsbabel.org/htmldoc-development/fmt_holux.html
  - https://github.com/gpsbabel/gpsbabel/blob/master/holux.h
  - https://github.com/gpsbabel/gpsbabel/blob/master/holux.cc
```
