### ISSUE TITLE
Alan Map500 GPS Tracklog

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#378]
```yaml
meta:
  id: gps_alan_wpr_trl
  title: Alan Map500 GPS Tracklog
  application:
    - Alan Map500
    - GPSBabel
  file-extension:
    - wpr
    - trl

doc: |
  Format of waypoints used by Alan gps receivers.

doc-ref:
  - https://www.gpsbabel.org/htmldoc-development/fmt_alantrl.html
  - https://github.com/gpsbabel/gpsbabel/blob/master/alan.cc
```
