### ISSUE TITLE
Bunshell GPS Trail

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#379]
```yaml
meta:
  id: gps_bunshell_trl
  title: Bunshell GPS Trail
  application: Bunshell receivers
  file-extension: trl

doc: |
  File format used in Bunshell GPS receivers

doc-ref:
  - https://www.gpsbabel.org/htmldoc-development/fmt_bushnell_trl.html
  - https://github.com/gpsbabel/gpsbabel/blob/master/bushnell_trl.cc

seq:
  - id: points
    type: point
    repeat: eof
types:
  point:
    seq:
      - id: lat
        type: fp
      - id: lon
        type: fp
    types:
      fp:
        seq:
          - id: raw
            type: s4
        instances:
          value:
            value: raw / 10000000.
```
