### ISSUE TITLE
Google Navigator Tracklines

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#380]
```yaml
meta:
  id: gps_google_navigator_trl
  title: Google Navigator Tracklines
  application: Google Navigator
  file-extension: trl
  xref:
    wikidata: Q

doc: |
  File format to save logs used in old Google Navigator

doc-ref:
  - https://www.gpsbabel.org/htmldoc-development/fmt_gnav_trl.html

seq:
  - id: points
    type: point
    repeat: eos

types:
  point:
    seq:
      - id: timestamp
        type: s4
     - id: lat
       type: f4
     - id: lon
       type: f4
     - id: alt
       type: f4
       doc: "ToDo: rotated left by eight bits"
```
