### ISSUE TITLE
EasyGPS

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#383]
```yaml
meta:
  id: easygps_poi
  title: EasyGPS format
  application: EasyGPS

doc: | 
  EasyGPS POI format

doc-ref:
  - https://www.gpsbabel.org/htmldoc-development/fmt_easygps.html
  - https://github.com/gpsbabel/gpsbabel/blob/e1e195beca8e0f24ca0e41c02d1986af13865cd0/easygps.cc#L75L146 
```
