### ISSUE TITLE
Geogrid-Viewer Overlay

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#384]
```yaml
meta:
  id: gps_geogrid_viewer_overlay
  title: Geogrid-Viewer Overlay
  application: Geogrid-Viewer
  file-extension: ovl

doc: |
  Maps of Geogrid-Viewer

doc-ref:
  - https://github.com/gpsbabel/gpsbabel/blob/e1e195beca8e0f24ca0e41c02d1986af13865cd0/ggv_bin.cc
  - https://www.gpsbabel.org/htmldoc-development/fmt_ggv_bin.html
```
