### ISSUE TITLE
Geogrid-Viewer Tracklog

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#385]
```yaml
meta:
  id: gps_geogrid_viewer_tracklog
  title: Geogrid-Viewer Tracklog
  application: Geogrid-Viewer
  file-extension: log

doc: |
  Tracklogs of Geogrid-Viewer

doc-ref:
  - https://github.com/gpsbabel/gpsbabel/blob/e1e195beca8e0f24ca0e41c02d1986af13865cd0/ggv_log.cc
  - https://www.gpsbabel.org/htmldoc-development/fmt_ggv_log.html
```
