### ISSUE TITLE
DeLorme Topo USA map

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#386]
```yaml
meta:
  id: gps_delorme_map_an1
  title: DeLorme Topo USA map
  application: DeLorme Topo USA
  file-extension: an1

doc: |
  Format used by DeLorme Topo USA

doc-ref:
  - https://www.gpsbabel.org/htmldoc-development/fmt_an1.html
  - https://github.com/gpsbabel/gpsbabel/blob/e1e195beca8e0f24ca0e41c02d1986af13865cd0/an1.cc
```
