### ISSUE TITLE
DeLorme Street Atlas Route

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#387]
```yaml
meta:
  id: gps_delorme_street_atlas_rte
  title: DeLorme Street Atlas Route
  application: DeLorme Street Atlas
  file-extension: 
    - anr
    - rte
    - rtd
doc: |
  A GPS track of DeLorme Street Atlas

doc-ref:
  - https://www.gpsbabel.org/htmldoc-development/fmt_saroute.html
  - https://github.com/gpsbabel/gpsbabel/blob/master/saroute.cc
```
