### ISSUE TITLE
Quram QMG boot/shutdown animation

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#393]
```yaml
meta:
  id: quram_qmage
  title: Quram QMG boot/shutdown animation
  application: Samsung phones
  file-extension: qmg

doc: |
  A proprietary image format used in Samsung phones.

doc-ref:
  - https://googleprojectzero.blogspot.com/2020/07/mms-exploit-part-1-introduction-to-qmage.html
  - https://googleprojectzero.blogspot.com/2020/07/mms-exploit-part-2-effective-fuzzing-qmage.html
  - https://docs.samsungknox.com/dev/knox-sdk/create-custom-animations.htm
  - https://forum.xda-developers.com/t/how-to-create-your-own-qmg-boot-animations-must-be-rooted.2217795/
```
