### ISSUE TITLE
GSD4t protocol

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#394]
```yaml
meta:
  id: gsd4t
  title: A proprietary protocol used to interact to GPS chips
  application: 

doc: |
  Some Samsung Galaxy phones use chips using this protocol.

doc-ref:
  - https://github.com/mnalis/gsd4t_parser
  - https://redmine.replicant.us/projects/replicant/wiki/GSD4t
  - https://github.com/E3V3A/GSD4t
```
