### ISSUE TITLE
Universal Disk Format

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#395]
```yaml
meta:
  id: universal_disk_format
  title: Universal Disk Format
  file-extension: udf
  xref:
    iso: 13346
    justsolve: Universal_Disk_Format
    ecma: 167
    wikidata: Q853645

doc: |
  Universal Disk Format is a standard of a filesystem for optical disks.

doc-ref:
  - http://www.osta.org/specs/index.htm
  - https://wiki.osdev.org/UDF
```
