### ISSUE TITLE
Zlib

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#396]
```yaml
meta:
  id: zlib_compression
  title: ZLib-compressed blocks
  application: zlib
  xref:
    justsolve: Zlib
    mime: application/zlib
    rfc: 1950
    wikidata: Q207240

doc: |
  Blocks compressed with zlib - a compression format designed by Mark Adler

doc-ref:
  - https://github.com/madler/zlib/blob/master/doc/rfc1950.txt
```
