### ISSUE TITLE
File Allocation Table

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#397]
```yaml
meta:
  id: fat
  title: File Allocation Table
  application:
    - MS DOS
    - MS Windows
    - UEFI
  xref:
    justsolve: FAT32
    wikidata: Q190167
  

doc: |
  An obsolete file system used in old MS OSes.

doc-ref:
  - https://github.com/YC/fat-fuse
  - https://wiki.osdev.org/FAT
```
