### ISSUE TITLE
Extended File Allocation Table

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#398]
```yaml
meta:
  id: exfat
  title: Extended File Allocation Table
  application:
    - MS Windows
  xref:
    justsolve: ExFAT
    wikidata: Q306233

doc: |
  A modernized obsolete file system used for storage on flash.

doc-ref:
  - https://docs.microsoft.com/en-us/windows/win32/fileio/exfat-specification
  - https://github.com/picrap/ExFat
```
