### ISSUE TITLE
Cryo HSQ

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#405]
```yaml
meta:
  id: cryo_hsq
  title: Cryo HSQ
  application: Cryo games

doc: |
  A compression format used in Cryo games, such as Dune 1

doc-ref:
  - https://github.com/elyosh/scummvm-cryo/blob/master/hsq.cpp
  - https://github.com/elyosh/scummvm-cryo/blob/master/hsq.h
```
