### ISSUE TITLE
Ballerina Intermediate Representation

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#406]
```yaml
meta:
  id: bir
  title: Ballerina Intermediate Representation
  application: Ballerina Language
  file-extension: bir
  endian: be
  license: Apache 2.0
doc-ref: https://github.com/ballerina-platform/ballerina-lang/blob/master/docs/compiler/bir-spec.md
```

```yaml
WiP: https://github.com/ballerina-platform/ballerina-lang/blob/master/docs/bir-spec/src/main/resources/kaitai/bir.ksy
```
