### ISSUE TITLE
Apache Lucene Compound File Entry Table

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#407]
```yaml
meta:
  id: lucene_cfe
  title: Apache Lucene Compound File Entry Table
  application: Apache Lucene # and software using it, such as ElasticSearch and DocFetcher
  file-extension: cfe
  licehse: Apache-2.0
  encoding: utf-8
  endian: be
  imports:
    - /common/vlq_base128_le

doc: |
  Apache Lucene Compound File Entry Table is a kind of filesystem or serialization format within a file. Prevents systems from running off file descriptors.

doc-ref:
  - https://lucene.apache.org/core/8_7_0/core/org/apache/lucene/codecs/lucene50/Lucene50CompoundFormat.html

seq:
  - id: header
    type: index_header
  - id: count
    -orig-id: FileCount
    type: vlq_base128_le
  - id: file
    type: file
    repeat: expr
    repeat-expr: count.value
  - id: footer
    type: codec_footer

instances:
  header_signature:
    value: 0x3fd76c17
    -orig-id:  CODEC_MAGIC
  footer_signature:
    value: ~ header_signature
    -orig-id:  FOOTER_MAGIC


types:
  oid:
    seq:
      - id: value
        size: 16

  codec_header :
    -orig-id: CodecHeader
    seq:
      - id: signature
        -orig-id: Magic
        type: u4
        valid: _root.header_signature
      - id: codec_name
        -orig-id: CodecName
        type: strz
        doc: This is a string to identify this file
      - id: version
        type: u4
        doc: Records the version of the file

  object_suffix:
    seq:
      - id: size
        type: u1
      - id: suffix
        size: size

  index_header:
    -orig-id: IndexHeader
    seq:
      - id: codec_header
        -orig-id: CodecHeader
        type: codec_header
      - id: oid
        type: oid
      - id: suffix
        type: object_suffix

  file_v3:
    seq:
      - id: codec_header
        -orig-id: CodecHeader
        type: u4 # Long
      - id: oid
        -orig-id: ObjectID
        type: strz

  file_v3:
    seq:
      - id: offset
        -orig-id: DataOffset
        type: u4 # Long
      - id: file_name
        -orig-id: FileName
        type: strz

  file_v5:
    seq:
      - id: file_name
        -orig-id: FileName
        type: strz
      - id: offset
        -orig-id: DataOffset
        type: u8 # UInt64
      - id: size
        -orig-id: DataLength
        type: u8 # UInt64

    instances:
      data:
        pos: offset
        size: size

```
