### ISSUE TITLE
Fossil VCS/SCM delta/patch

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#413]
```yaml
meta:
  id: fossil_patch_blob
  title: Fossil VCS/SCM delta/patch
  application: Fossil SCM

doc: |
  A format for a patch used in Fossil SCM. Fossil stores history as a sequence of patches.

doc-ref:
  - https://www.fossil-scm.org/index.html/doc/tip/www/delta_format.wiki
  - https://github.com/ggicci/python-fossil-delta
```
