### ISSUE TITLE
Gentoo XPAK

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#414]
```yaml
meta:
  id: gentoo_xpak
  title: Gentoo XPAK
  application: Gentoo portage

doc: |
  Contains metadata about conditions in which a package was built.

doc-ref:
  - https://www.mankier.com/5/xpak
  - https://github.com/gentoo/portage/blob/master/lib/portage/xpak.py
```
