### ISSUE TITLE
Android binary XML

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#450]
```yaml
meta:
  id: android_binary_xml
  title: Android binary XML
  application: Android
  -filename-regexp: (?:resources\.arsc|.+\.xml)  # In resources of APKs most of XML files are encoded like this

doc: |
  A file format storing some metadata in Android APKs.

doc-ref:
  - https://android.googlesource.com/platform/frameworks/base.git/+/master/libs/androidfw/include/androidfw/ResourceTypes.h
  - https://github.com/rednaga/axmlprinter
  - https://github.com/antitree/AxmlParserPY
  - https://github.com/hradecek/apk2xml
  - https://github.com/armijnhemel/binaryanalysis-ng/blob/534afee3c8862776251084a0e27bc26abf3da862/src/bangandroid.py#L1726
```

@armijnhemel
