### ISSUE TITLE
Android timezone info

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#451]
```yaml
meta:
  id: android_timezone_info
  title: Android timezone info
  application:
    - Android
    - ZoneCompactor
    - tzupdater
  -filename-regexp: tzdata

doc: |
  A file used in Android devices to store info about timezones.

doc-ref:
  - https://android.googlesource.com/platform/system/timezone/+/master/input_tools/android/zone_compactor/main/java/ZoneCompactor.java
```
@armijnhemel, @ian-abbott, @meefik
