### ISSUE TITLE
Mapsforge binary Map

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#452]
```yaml
meta:
  id: mapsforge_map
  title: Mapsforge Map
  application: Mapsforge  #  all the apps using this library
  file-extension: map

doc: |
  MapForge binary map is splitted across multiple files like this one, each one contains data at specific resolution (`zoom level` they call it).

doc-ref:
  - https://github.com/mapsforge/mapsforge/blob/master/docs/Specification-Binary-Map-File.md
```
@armijnhemel
