### ISSUE TITLE
splitting an array of bytes

### ISSUE THREAD

**Issue by armijnhemel** [kaitai-io/kaitai_struct_formats#466]
I currently am looking at a specification, where there is a blob of bytes at some offset that consists of NUL terminated strings, but unsure how to process that. I couldn't find it in the user guide or documentation. What is the recommended way?

Currently I have something like this:

```
instances:
  strings_block:
    pos: strings_block_offset
    size: size_dt_strings
    type: strings
    repeat: eos

types:
  strings:
    seq:
      - id: string
        type: strz
        encoding: ASCII
```

but that only gives me the first string.
