### ISSUE TITLE
CHIP-8

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#468]
```yaml
meta:
  id: chip8
  title: CHIP-8
  xref: 
    justsolve: CHIP-8
    wikidata: Q1023623

doc: |
  CHIP-8 is a virtual-machine-based language designed specially for developing 2D video games in 197x.

doc-ref:
  - https://storage.googleapis.com/wzukusers/user-34724694/documents/5c83d6a5aec8eZ0cT194/CHIP-8%20Classic%20Manual%20Rev%201.3.pdf
  - http://www.mattmik.com/files/chip8/extensions/CHIP8ExtensionsReference.pdf
  - https://git.sr.ht/~paulcacheux/Chip8/tree/master/item/src/instructions.rs
```
