### ISSUE TITLE
Document list of supported encodings

### ISSUE THREAD

**Issue by tegob** [kaitai-io/kaitai_struct_formats#5]
https://github.com/kaitai-io/kaitai_struct/wiki/Expressions has this example:

```
seq:
  - id: filename_len
    type: u4
  - id: filename
    type: str
    size: filename_len
    encoding: UTF-8
```

Other than `UTF-8`, which encodings are supported? Would be useful to have this list documented somewhere :)
