### ISSUE TITLE
vfat boot_sector needs extra sanity checks

### ISSUE THREAD

**Issue by armijnhemel** [kaitai-io/kaitai_struct_formats#507]
I have been digging a bit through the VFAT specs and it seems that the boot_sector needs some extra sanity checks.

According to the official docs:

```
jump instruction to boot code. This field has two allowed forms: 
jmpBoot[0] = 0xEB, jmpBoot[1] = 0x??, jmpBoot[2] = 0x90  
and 
jmpBoot[0] = 0xE9, jmpBoot[1] = 0x??, jmpBoot[2] = 0x?? 
```

What would be the best way? Split the jmp_instruction field? Create new types with extra sanity checks?

**Comment by armijnhemel** [comment]
Just in case someone in the future bumps into this, I fixed this using an extra instance:

```
    instances:
      is_valid:
        value: '(jmp_1 == 0xeb and jmp_3 == 0x90) or jmp_1 == 0xe9'
```

and then using a `valid` `expr`:

```
      - id: jmp_instruction
        type: jmp_instruction
        valid:
          expr: jmp_instruction.is_valid

```
