### ISSUE TITLE
Zeno

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#523]
```yaml
meta:
  id: zeno
  title: Zeno
  file-extension: zeno
  xref:
    justsolve: Zeno
  encoding: utf-8
  endian: le
doc: |
  An obsolete format (superseded by ZIM) for storing pags in MediaWiki markup language.

doc-ref:
  - https://wiki.openzim.org/wiki/Zeno_File_Format
```
