### ISSUE TITLE
Yet Another Flash File System, version 2

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#524]
```yaml
meta:
  id: yaffs2
  title: Yet Another Flash File System, version 2
  application: 
  file-extension: 
  xref:
    forensicswiki: YAFFS2
    sleuthkitwiki: YAFFS2
    justsolve: YAFFS
    wikidata: Q2492291

doc: |
  A file system for flash storage.

doc-ref:
  - https://yaffs.net/documents
```
