### ISSUE TITLE
Universal 3D

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#525]
```yaml
meta:
  id: u3d
  title: Universal 3D
  application: 
  file-extension: 
  xref:
    justsolve: U3D
    loc: fdd/fdd000491
    mime: model/u3d
    pronom:
     - fmt/702
    ecma: 363
    ffdg: 3d/u3d
    wikidata: Q974182

doc: |
  A format for storing 3d models for CAD purposes.

doc-ref:
  - https://www.ecma-international.org/wp-content/uploads/ECMA-363_4th_edition_june_2007.pdf
```

```yaml
WiP: https://github.com/kaitai-io/kaitai_struct/issues/476#issue-364073480
```

@joshewilliams
