### ISSUE TITLE
AT Attachment

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#526]
```yaml
meta:
  id: ata
  title: AT Attachment
  xref:
    incits:
      - 317-1998
      - 340-2000
      - 361-2002
      - 558-202x
    ansi:
      - X3.221-1994
      - X3.279-1996
    iso:
      - 24739-1:2009
      - 17760-101:2015
      - 14776-154:201x
    wikidata: Q230360

doc: |
  A standard for controlling storage devices.

doc-ref:
  - https://wiki.osdev.org/ATA_Command_Matrix
  - https://standards.incits.org/apps/group_public/download.php/128286/livelink ACS-5 Revision 10 March 3, 2021
  - https://standards.incits.org/apps/group_public/download.php/93215/livelink ACS-4 Revision 20 October 26, 2017
  - https://web.archive.org/web/20181123105648if_/http://t13.org:80/Documents/UploadedDocuments/docs2017/di529r18-ATAATAPI_Command_Set_-_4.pdf Revision 18 August 4, 2017
  - https://standards.incits.org/apps/group_public/download.php/93215/livelink ACS-4 Revision 20 October 26, 2017
  - https://standards.incits.org/apps/group_public/download.php/82500/livelink SAT-3 Revision 06 23 September, 2016
  - https://standards.incits.org/apps/group_public/download.php/59850/eb-2014-00740-Public-review-%20register-INCITS-517-201x-Comments-due-11-24-2014.pdf SAT-3 Revision 07 15 September, 2014
  - https://read.seas.harvard.edu/cs161/2019/pdf/ata-atapi-8.pdf ACS-3 Revision 5 October 28, 2013
  - https://people.freebsd.org/~imp/asiabsdcon2015/works/d2161r5-ATAATAPI_Command_Set_-_3.pdf ACS-3 Revision 5 October 28, 2013
  - https://web.archive.org/web/20190210182445if_/http://www.t13.org/Documents/UploadedDocuments/docs2009/d2015r2-ATAATAPI_Command_Set_-_2_ACS-2.pdf ACS-2 Revision 2 August 3, 2009
  - https://web.archive.org/web/20180814124111if_/http://www.t13.org/documents/UploadedDocuments/docs2007/D1699r4a-ATA8-ACS.pdf ATA8-ACS Revision 4a May 21, 2007
  - https://tc.gts3.org/cs3210/2016/spring/r/hardware/ATA8-ACS.pdf Revision 4a May 21, 2007
  - https://pdos.csail.mit.edu/6.828/2005/readings/hardware/ATA-d1410r3a.pdf
  - https://hddguru.com/download/documentation/ATA-ATAPI-standard-8/d1699r2b-ATA8-Command-Set.pdf
  - https://hddguru.com/download/documentation/ATA-ATAPI-standard-8/d1700r2-ATA8-Architecture-Model.pdf
  - https://web.archive.org/web/20190606080908if_/http://www.t13.org/Documents/UploadedDocuments/docs2007/D1532v1r4b-AT_Attachment_with_Packet_Interface_-_7_Volume_1.pdf ATA/ATAPI-7 V1 Revision 4b 21 April 2004
  - https://hddguru.com/download/documentation/ATA-ATAPI-standard-7/d1532v1r4b-ATA-ATAPI-7-1.pdf
  - https://web.archive.org/web/20190606080907if_/http://www.t13.org/Documents/UploadedDocuments/docs2007/D1532v2r4b-AT_Attachment_with_Packet_Interface_-_7_Volume_2.pdf ATA/ATAPI-7 V2 Revision 4b 21 April 2004
  - https://hddguru.com/download/documentation/ATA-ATAPI-standard-7/d1532v2r4b-ATA-ATAPI-7-2.pdf
  - https://web.archive.org/web/20190606080907if_/http://www.t13.org/Documents/UploadedDocuments/docs2007/D1532v3r4b-AT_Attachment_with_Packet_Interface_-_7_Volume_3.pdf ATA/ATAPI-7 V3 Revision 4b 21 April 2004
  - https://hddguru.com/download/documentation/ATA-ATAPI-standard-7/d1532v3r4b-ATA-ATAPI-7-3.pdf
  - https://web.archive.org/web/20190807012435if_/http://www.t13.org/Documents/UploadedDocuments/project/d1410r3b-ATA-ATAPI-6.pdf ATA/ATAPI-6 Revision 3b 26 February 2002
  - https://hddguru.com/download/documentation/ATA-ATAPI-standard-6/ATA-ATAPI-6.pdf
  - https://www.seagate.com/support/disc/manuals/ata/d1153r17.pdf ATA/ATAPI-5 Revision 3 29 February 2000
  - https://web.archive.org/web/20190606080909if_/http://www.t13.org/documents/UploadedDocuments/project/d1321r3-ATA-ATAPI-5.pdf ATA/ATAPI-5 Revision 3 29 February 2000
  - https://hddguru.com/download/documentation/ATA-ATAPI-standard-5/ATA-ATAPI-5.pdf
  - https://web.archive.org/web/20070711015221if_/http://www.t13.org:80/Documents/UploadedDocuments/project/e01122r0.pdf NCITS 340-2000 ATA/ATAPI-5 erratum
  - https://web.archive.org/web/20191117063344if_/http://www.t13.org/documents/UploadedDocuments/project/d1153r18-ATA-ATAPI-4.pdf ATA/ATAPI-4 Revision 18 19 August 1998
  - https://www.mit.edu/afs/sipb/contrib/doc/specs/protocol/ata/d1153r18.pdf
  - https://web.archive.org/web/20070204032206if_/http://www.t13.org:80/Documents/UploadedDocuments/project/ATA4erra.pdf ATA/ATAPI-4 ANSI NCITS 317-1998 (erratum)
  - https://web.archive.org/web/20190606080900if_/https://www.t13.org/Documents/UploadedDocuments/project/d0948r4c-ATA-2.pdf ATA-2 Revision 4c March 18, 1996
  - http://hddguru.com/download/documentation/ATA-ATAPI-standard-2/d0948r4c_ATA-ATAPI-2.pdf
  - https://web.archive.org/web/20190831040750if_/https://www.t13.org/documents/UploadedDocuments/project/d0791r4c-ATA-1.pdf Revision 4c
  - https://hddguru.com/download/documentation/ATA-ATAPI-standard-1/d0791r4c_ATA-ATAPI-1.pdf 
```
