### ISSUE TITLE
Unsorted Block Image File System

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#527]
```yaml
meta:
  id: ubifs
  title: Unsorted Block Image File System
  application:
    - Linux
  xref:
    justsolve: UBIFS
    wikidata: Q1018125

doc: |
  A filesystem for flash storage that is a successor of JFFS2

doc-ref:
  - https://git.infradead.org/mtd-www.git/blob/HEAD:/doc/ubifs.pdf
  - https://git.infradead.org/mtd-www.git/blob/HEAD:/doc/ubifs_whitepaper.pdf
  - https://git.infradead.org/mtd-www.git/blob_plain/HEAD:/faq/ubifs.xml
  - https://github.com/torvalds/linux/tree/master/fs/ubifs
  - https://github.com/torvalds/linux/blob/master/Documentation/filesystems/ubifs.rst
  - https://github.com/torvalds/linux/blob/master/Documentation/filesystems/ubifs-authentication.rst
  - https://lwn.net/Articles/275706/
```

```yaml
WiP: https://github.com/armijnhemel/binaryanalysis-ng/blob/fc4ce813c155fa3b7fa794edb55c09387a3ea773/src/parsers/filesystem/ubifs/ubifs.ksy
```
