### ISSUE TITLE
Hierarchical Data Format, version 5

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#528]
```yaml
meta:
  id: hdf5
  title: Hierarchical Data Format, version 5
  file-extension::
    - hdf
    - h5
    - hdf5
    - he5
  tags:
    - archive
    - filesystem
  xref:
    fileformat: hdf
    justsolve: HDF5
    loc: fdd/fdd000229
    mime:
      - application/x-hdf
      - application/x-hdf5
    pronom:
     - fmt/286
    uti: 
    wikidata: Q1069215

doc: |
  A format for storing datasets.

doc-ref:
  - https://support.hdfgroup.org/HDF5/doc/H5.format.html
  - https://cyrille.rossant.net/moving-away-hdf5/
```
