### ISSUE TITLE
Network Common Data Form

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#529]
```yaml
meta:
  id: net_cdf
  title: Network Common Data Form
  file-extension:
    - nc
    - cdf
  xref:
    justsolve: NetCDF
    loc:
      - fdd/fdd000339
      - fdd/fdd000332
      - fdd/fdd000330
    mime:
      - application/netcdf
      - application/x-netcdf
    pronom:
     - fmt/283
    wikidata: Q1361922

doc: |
  A format for datasets, usually used for geospatial applications.
  Sample files can be found here: https://www.unidata.ucar.edu/software/netcdf/examples/files.html

doc-ref:
  - https://www.unidata.ucar.edu/software/netcdf/documentation/historic/netcdf/Structure.html
  - https://github.com/Unidata/netcdf-c
```
