### ISSUE TITLE
DNS Firewall Enforcer ("dnsfire")

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#530]
```yaml
meta:
  id: dnsfire
  title: DNS Firewall Enforcer
  application: DNS Firewall Enforcer

doc: |
  "DNS Firewall Enforcer" is a proof-of-concept censorship and surveillance enforcement software, that forbids any connections to the IPs which addresses have not been previously resolved via DNS. This is used to blackamail users into actually using operator's DNS server, so he can spy on and tamper with (i.e. for the purposes of censorship, when disallowed services are blocked by DNS records) users' DNS queries. Also blocks everything not resolvable via DNS.

doc-ref:
  - https://github.com/wupeka/dnsfire/blob/ea2721c07cb3ccbde6a635f7a309dc3370096528/bind9-dnsfire.patch#L108
```
