### ISSUE TITLE
zip: dates 00-00-1980 are (in)valid?

### ISSUE THREAD

**Issue by armijnhemel** [kaitai-io/kaitai_struct_formats#562]
I am not sure whether or not to file this one against `zip.ksy` or `/common/dos_datetime.ksy`, so perhaps it needs to be moved.

I am currently looking at the contents of a ZIP-file inside a Chrome extension. In `zip.ksy` the standard MS-DOS format is used for the date in (amongst others) the local file header. In the example I am looking at ( https://github.com/GoogleChrome/chrome-extensions-samples/blob/main/mv2-archive/api/permissions/extension-questions.crx ) I can see the following:

```
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  00-00-1980 00:00   images/
      476  00-00-1980 00:00   manifest.json
      312  00-00-1980 00:00   options.html
     1345  00-00-1980 00:00   options.js
      177  00-00-1980 00:00   popup.html
     1424  00-00-1980 00:00   popup.js
     7008  00-00-1980 00:00   images/icon.png
---------                     -------
    10742                     7 files

```

In `/common/dos_datetime.ksy` there are these sanity checks:

```
  date:
    -webide-representation: "{padded_year}-{padded_month}-{padded_day}"
    seq:
      - id: day
        type: b5
        valid:
          min: 1
      - id: month
        type: b4
        valid:
          min: 1
          max: 12
```

and that obviously fails.

There are three solutions:

1. reject this file as invalid - I think this would be incorrect
2. drop the sanity checks in `/common/dos_datetime.ksy` - perhaps this isn't correct either
3. do not use `dos_datetime` in the ZIP specification - not ideal, but perhaps the best
