### ISSUE TITLE
MA-FSA Go impl binary format

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#564]
```yaml
meta:
  id: ma_fsa_dag_go
  title: MA-FSA serialized DAG
  application: MA-FSA for Go

doc: |
  MA-FSA is a method to store a compressed key-value mapping for strings. Nice for paths reusing tokens. There are multiple impls, each kne has an own format.

doc-ref:
  - https://github.com/Shugyousha/mafsa
```
