### ISSUE TITLE
libpsl MA-FSA serialized DAG

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#567]
```yaml
meta:
  id: ma_fsa_dag_libpsl
  title: libpsl MA-FSA serialized DAG
  application:
    - libpsl
    - psl-make-dafsa
  application: MA-FSA for libpsl

doc: |
  MA-FSA, aka DAWG, is a method to store a compressed key-value mapping for strings as keys. Nice for paths reusing tokens. There are multiple impls, each one has an own format.

doc-ref:
  - https://github.com/rockdaboot/libpsl
```
