### ISSUE TITLE
MA-FSA serialized DAG in dawgdic format

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#568]
```yaml
meta:
  id: ma_fsa_dag_dawgdic
  title: MA-FSA serialized DAG in dawgdic format
  application:
    - dawgdic-build
    - dawgdic-find

doc: |
  MA-FSA, aka DAWG, is a method to store a compressed key-value mapping for strings as keys. Nice for paths reusing tokens. There are multiple impls, each one has an own format.

doc-ref:
  - https://github.com/stil/dawgdic
  - https://github.com/pytries/DAWG-Python
  - https://github.com/pytries/DAWG
```
