### ISSUE TITLE
JBIG2 compressed image

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#574]
```yaml
meta:
  id: jbig2
  title: JBIG2 compressed image
  file-extension: jbig2
  application:
    - PDF
    - JPEG 2000
    - FORCEDENTRY
  xref:
    ansi: 
    din: 
    fileformat: mirror/egff/ch09_07
    iso: 14492
    itu-t: 88
    justsolve: JBIG2
    loc: fdd/fdd000010
    wikidata: Q1143961

doc: |
  JBIG2 is a Turing-complete (in some circumstances) file format used in fax machines, PDFs and JPEG 2000. It aggressively deduplicates the image and in order to enable lossless compression stores additional info in a form of blocks to be apllied to inputs and outputs via various bitwise operators.

doc-ref:
  - https://github.com/apache/pdfbox-jbig2
  - https://github.com/pts/pdfsizeopt-jbig2
  - https://github.com/levigo/jbig2-imageio
  - https://github.com/ArtifexSoftware/jbig2dec
  - https://www.cl.cam.ac.uk/~mgk25/jbigkit/
  - https://github.com/rhatlapa/pdfjbim
  - https://googleprojectzero.blogspot.com/2021/12/a-deep-dive-into-nso-zero-click.html
```
