### ISSUE TITLE
Compact C Type Format

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#604]
```yaml
meta:
  id: compact_c_type_format
  title: Compact C Type Format
  application:
    - gcc
    - libctf
    - libdtrace-ctf

doc: |
  A compact format to store debug information with main accent on the needs of C language.

doc-ref:
  - https://www.freebsd.org/cgi/man.cgi?query=ctf&sektion=5
  - https://raw.githubusercontent.com/wiki/oracle/binutils-gdb/files/ctf-spec.pdf
  - https://lwn.net/Articles/795384/
  - https://github.com/lovasko/libctf
  - https://github.com/oracle/libdtrace-ctf
```
