### ISSUE TITLE
Mozilla Firefox Startup Cache v2

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#613]
```yaml
meta:
  id: mozilla_startup_cache
  title: Mozilla Firefox Startup Cache
  application: Mozilla Firefox
  -filename-regex: "/^startupCache\\.(?<wordSizeInBytes>\\d+)\\.(?<endiannes>big|little)$/"

doc: |
  Mozilla Firefox uses cache files to speed-up its loading.

doc-ref:
  - https://wiki.mozilla.org/StartupCache
  - https://searchfox.org/mozilla-central/source/startupcache/StartupCache.h
  - https://searchfox.org/mozilla-central/source/startupcache/StartupCache.cpp
```
