### ISSUE TITLE
Windows NT keyboard tables

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct_formats#626]
```yaml
meta:
  id: windows_kbd_tables
  -orig-id: _KBDTABLES
  title: Windows NT keyboard tables
  application:
    - Microsoft Windows
    - ReactOS
    - Microsoft Keyboard Layout Creator
    - KbdEdit
    - KLM32
    - Win32Keyboard
    - kbdasm
  file-extension: dll
  xref:
    wikidata: Q4044227

doc: |
  Keyboard layout table used in NT-based versions of Windows. Pointer to it is returned by ` KbdLayerDescriptor`.

doc-ref:
  - https://habr.com/ru/post/301882/
  - https://github.com/grompe/kbdasm/blob/master/article.txt # the same article as on Habr
  - https://github.com/awakecoding/Win32Keyboard
  - https://github.com/reactos/reactos/blob/master/sdk/include/ndk/kbd.h
```
