### ISSUE TITLE
RPM: not all strings UTF-8

### ISSUE THREAD

**Issue by armijnhemel** [kaitai-io/kaitai_struct_formats#672]
In the current `rpm.ksy` the `encoding` for strings is set to UTF-8. There are RPM files that fail to parse, because as it turns out not everyone has been playing nice with encodings.

An example is this file from Fedora Core 3:

https://archives.fedoraproject.org/pub/archive/fedora/linux/core/3/x86_64/os/Fedora/RPMS/bash-3.0-17.x86_64.rpm

One of the tags is a `record_type_string_array` related to ChangeLogs and some people seem to have used Latin-1 characters instead.

```
Trond Eivind Glomsr\xf8d <teg@redhat.com> 2.0.5a-10
```

Currently `record_type_string_array` is defined as follows:

```
  record_type_string_array:
    params:
      - id: num_values
        type: u4
    seq:
      - id: values
        type: strz
        repeat: expr
        repeat-expr: num_values
```

and the default encoding is UTF-8, so this will obviously not work. I don't know how I could fix this.
