### ISSUE TITLE
How to get offset of every structure in Java?

### ISSUE THREAD

**Issue by Stefman87** [kaitai-io/kaitai_struct_formats#713]
I need to get the offset of every structure. So, I created this class:

```
public abstract class MyStruct extends KaitaiStruct {
    protected long _startOffset;
    protected long _endOffset;
    protected String _structName;

    public MyStruct(KaitaiStream _io) {
        super(_io);
        this._structName = this.getClass().getSimpleName();
        this._startOffset = _io.pos();
    }

    protected void _endRead() {
        this._endOffset = _io.pos();
        System.out.printf(
            "Struct '%s' parsed at [0x%x..0x%x] (%d bytes)%n",
            _structName, _startOffset, _endOffset, _endOffset - _startOffset
        );
    }
   ...
}
```
And in Parser (Gif.java) in every `_read()` method of every structure I add `_endRead()`. For example:

```
    public static class Subblock extends MyStruct {
        public static Subblock fromFile(String fileName) throws IOException {
            return new Subblock(new ByteBufferKaitaiStream(fileName));
        }

        public Subblock(KaitaiStream _io) {
            this(_io, null, null);
        }

        public Subblock(KaitaiStream _io, MyStruct _parent) {
            this(_io, _parent, null);
        }

        public Subblock(KaitaiStream _io, MyStruct _parent, Gif _root) {
            super(_io);
            this._parent = _parent;
            this._root = _root;
            _read();
        }
        private void _read() {
            this.lenBytes = this._io.readU1();
            this.bytes = this._io.readBytes(lenBytes());
            _endRead();
        }
     ...
```
But it doesn't work as expected. For example I get this result:

```
Gif [0x0..0x40316]
  Header [0x0..0x6]
    magic: [B@568db2f2
    version: 89a
  LogicalScreenDescriptorStruct [0x6..0x13]
    colorTableSize: 256
    screenWidth: 312
    screenHeight: 312
    flags: 247
    bgColorIndex: 49
    pixelAspectRatio: 0
  ColorTable [0x0..0x768]
    entries:
      ColorTableEntry [0x0..0x3]
        red: 98
        green: 57
        blue: 49
```
As you see `ColorTable` starts at 0x0 that can't be possible.

Could anyone say what is the correct way to get the offset of every structure?
